//! Exact selected native field closure; derived from the frozen schema projection, not an oracle implementation.
use crate::{
    capability::{FeatureGateId, FieldAdmission, FieldCapability, KindCapability, KubernetesVersion, MergeStrategy},
    diagnostic::{Finding, FindingCode, Phase},
    model::{GroupVersionKind, ResourceScope},
};
use std::sync::LazyLock;
fn version(minor: u8) -> KubernetesVersion {
    KubernetesVersion::new(1, minor).unwrap_or(KubernetesVersion::MAX)
}
fn field(
    path: &'static str,
    first: u8,
    last: u8,
    feature_gate: Option<FeatureGateId>,
    merge: MergeStrategy,
) -> FieldCapability {
    FieldCapability {
        path,
        since: version(first),
        feature_gate,
        removed: (last < 37).then(|| version(last + 1)),
        deprecated: None,
        admission: FieldAdmission::Typed,
        merge,
        semantic_note: None,
    }
}

static FIELDS_0: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 37, None, MergeStrategy::Scalar),
    ]
});

static FIELDS_1: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/automountServiceAccountToken", 20, 37, None, MergeStrategy::Scalar),
        field("/imagePullSecrets", 20, 37, None, MergeStrategy::AtomicList),
        field("/imagePullSecrets/*", 20, 37, None, MergeStrategy::Object),
        field("/imagePullSecrets/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 37, None, MergeStrategy::Scalar),
        field("/secrets", 20, 37, None, MergeStrategy::MapList { keys: &["name"] }),
        field("/secrets/*", 20, 37, None, MergeStrategy::Object),
        field("/secrets/*/apiVersion", 20, 37, None, MergeStrategy::Scalar),
        field("/secrets/*/fieldPath", 20, 37, None, MergeStrategy::Scalar),
        field("/secrets/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/secrets/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/secrets/*/namespace", 20, 37, None, MergeStrategy::Scalar),
        field("/secrets/*/resourceVersion", 20, 37, None, MergeStrategy::Scalar),
        field("/secrets/*/uid", 20, 37, None, MergeStrategy::Scalar),
    ]
});

static FIELDS_2: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 37, None, MergeStrategy::Scalar),
        field("/rules", 20, 37, None, MergeStrategy::AtomicList),
        field("/rules/*", 20, 37, None, MergeStrategy::Object),
        field("/rules/*/apiGroups", 20, 37, None, MergeStrategy::AtomicList),
        field("/rules/*/apiGroups/*", 20, 37, None, MergeStrategy::Scalar),
        field("/rules/*/nonResourceURLs", 20, 37, None, MergeStrategy::AtomicList),
        field("/rules/*/nonResourceURLs/*", 20, 37, None, MergeStrategy::Scalar),
        field("/rules/*/resourceNames", 20, 37, None, MergeStrategy::AtomicList),
        field("/rules/*/resourceNames/*", 20, 37, None, MergeStrategy::Scalar),
        field("/rules/*/resources", 20, 37, None, MergeStrategy::AtomicList),
        field("/rules/*/resources/*", 20, 37, None, MergeStrategy::Scalar),
        field("/rules/*/verbs", 20, 37, None, MergeStrategy::AtomicList),
        field("/rules/*/verbs/*", 20, 37, None, MergeStrategy::Scalar),
    ]
});

static FIELDS_3: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 37, None, MergeStrategy::Scalar),
        field("/roleRef", 20, 37, None, MergeStrategy::Object),
        field("/roleRef/apiGroup", 20, 37, None, MergeStrategy::Scalar),
        field("/roleRef/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/roleRef/name", 20, 37, None, MergeStrategy::Scalar),
        field("/subjects", 20, 37, None, MergeStrategy::AtomicList),
        field("/subjects/*", 20, 37, None, MergeStrategy::Object),
        field("/subjects/*/apiGroup", 20, 37, None, MergeStrategy::Scalar),
        field("/subjects/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/subjects/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/subjects/*/namespace", 20, 37, None, MergeStrategy::Scalar),
    ]
});

static FIELDS_4: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/aggregationRule", 20, 37, None, MergeStrategy::Object),
        field(
            "/aggregationRule/clusterRoleSelectors",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/aggregationRule/clusterRoleSelectors/*",
            20,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/aggregationRule/clusterRoleSelectors/*/matchExpressions",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/aggregationRule/clusterRoleSelectors/*/matchExpressions/*",
            20,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/aggregationRule/clusterRoleSelectors/*/matchExpressions/*/key",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/aggregationRule/clusterRoleSelectors/*/matchExpressions/*/operator",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/aggregationRule/clusterRoleSelectors/*/matchExpressions/*/values",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/aggregationRule/clusterRoleSelectors/*/matchExpressions/*/values/*",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/aggregationRule/clusterRoleSelectors/*/matchLabels",
            20,
            37,
            None,
            MergeStrategy::Map,
        ),
        field(
            "/aggregationRule/clusterRoleSelectors/*/matchLabels/*",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 37, None, MergeStrategy::Scalar),
        field("/rules", 20, 37, None, MergeStrategy::AtomicList),
        field("/rules/*", 20, 37, None, MergeStrategy::Object),
        field("/rules/*/apiGroups", 20, 37, None, MergeStrategy::AtomicList),
        field("/rules/*/apiGroups/*", 20, 37, None, MergeStrategy::Scalar),
        field("/rules/*/nonResourceURLs", 20, 37, None, MergeStrategy::AtomicList),
        field("/rules/*/nonResourceURLs/*", 20, 37, None, MergeStrategy::Scalar),
        field("/rules/*/resourceNames", 20, 37, None, MergeStrategy::AtomicList),
        field("/rules/*/resourceNames/*", 20, 37, None, MergeStrategy::Scalar),
        field("/rules/*/resources", 20, 37, None, MergeStrategy::AtomicList),
        field("/rules/*/resources/*", 20, 37, None, MergeStrategy::Scalar),
        field("/rules/*/verbs", 20, 37, None, MergeStrategy::AtomicList),
        field("/rules/*/verbs/*", 20, 37, None, MergeStrategy::Scalar),
    ]
});

static FIELDS_5: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 37, None, MergeStrategy::Scalar),
        field("/roleRef", 20, 37, None, MergeStrategy::Object),
        field("/roleRef/apiGroup", 20, 37, None, MergeStrategy::Scalar),
        field("/roleRef/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/roleRef/name", 20, 37, None, MergeStrategy::Scalar),
        field("/subjects", 20, 37, None, MergeStrategy::AtomicList),
        field("/subjects/*", 20, 37, None, MergeStrategy::Object),
        field("/subjects/*/apiGroup", 20, 37, None, MergeStrategy::Scalar),
        field("/subjects/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/subjects/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/subjects/*/namespace", 20, 37, None, MergeStrategy::Scalar),
    ]
});

static FIELDS_6: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 37, None, MergeStrategy::Scalar),
        field("/spec", 20, 37, None, MergeStrategy::Object),
        field("/spec/maxReplicas", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/minReplicas", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/scaleTargetRef", 20, 37, None, MergeStrategy::Object),
        field("/spec/scaleTargetRef/apiVersion", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/scaleTargetRef/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/scaleTargetRef/name", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/spec/targetCPUUtilizationPercentage",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
    ]
});

static FIELDS_7: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 23, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 23, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 23, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 23, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 23, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 23, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 23, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 23, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 23, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            23,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 23, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 23, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 23, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 23, 37, None, MergeStrategy::Scalar),
        field("/spec", 20, 37, None, MergeStrategy::Object),
        field("/spec/behavior", 23, 37, None, MergeStrategy::Object),
        field("/spec/behavior/scaleDown", 23, 37, None, MergeStrategy::Object),
        field(
            "/spec/behavior/scaleDown/policies",
            23,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/behavior/scaleDown/policies/*",
            23,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/behavior/scaleDown/policies/*/periodSeconds",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/behavior/scaleDown/policies/*/type",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/behavior/scaleDown/policies/*/value",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/behavior/scaleDown/selectPolicy",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/behavior/scaleDown/stabilizationWindowSeconds",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/behavior/scaleUp", 23, 37, None, MergeStrategy::Object),
        field(
            "/spec/behavior/scaleUp/policies",
            23,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field("/spec/behavior/scaleUp/policies/*", 23, 37, None, MergeStrategy::Object),
        field(
            "/spec/behavior/scaleUp/policies/*/periodSeconds",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/behavior/scaleUp/policies/*/type",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/behavior/scaleUp/policies/*/value",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/behavior/scaleUp/selectPolicy",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/behavior/scaleUp/stabilizationWindowSeconds",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/maxReplicas", 23, 37, None, MergeStrategy::Scalar),
        field("/spec/metrics", 23, 37, None, MergeStrategy::AtomicList),
        field("/spec/metrics/*", 23, 37, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/containerResource",
            23,
            37,
            Some(FeatureGateId::HPAContainerMetrics),
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/containerResource/container",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/containerResource/name",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/containerResource/target",
            23,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/containerResource/target/averageUtilization",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/containerResource/target/averageValue",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/containerResource/target/type",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/containerResource/target/value",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/external", 23, 37, None, MergeStrategy::Object),
        field("/spec/metrics/*/external/metric", 23, 37, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/external/metric/name",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/metric/selector",
            23,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/external/metric/selector/matchExpressions",
            23,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/external/metric/selector/matchExpressions/*",
            23,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/external/metric/selector/matchExpressions/*/key",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/metric/selector/matchExpressions/*/operator",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/metric/selector/matchExpressions/*/values",
            23,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/external/metric/selector/matchExpressions/*/values/*",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/metric/selector/matchLabels",
            23,
            37,
            None,
            MergeStrategy::Map,
        ),
        field(
            "/spec/metrics/*/external/metric/selector/matchLabels/*",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/external/target", 23, 37, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/external/target/averageUtilization",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/target/averageValue",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/target/type",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/target/value",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/object", 23, 37, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/object/describedObject",
            23,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/object/describedObject/apiVersion",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/describedObject/kind",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/describedObject/name",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/object/metric", 23, 37, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/object/metric/name",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/metric/selector",
            23,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/object/metric/selector/matchExpressions",
            23,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/object/metric/selector/matchExpressions/*",
            23,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/object/metric/selector/matchExpressions/*/key",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/metric/selector/matchExpressions/*/operator",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/metric/selector/matchExpressions/*/values",
            23,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/object/metric/selector/matchExpressions/*/values/*",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/metric/selector/matchLabels",
            23,
            37,
            None,
            MergeStrategy::Map,
        ),
        field(
            "/spec/metrics/*/object/metric/selector/matchLabels/*",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/object/target", 23, 37, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/object/target/averageUtilization",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/target/averageValue",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/target/type",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/target/value",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/pods", 23, 37, None, MergeStrategy::Object),
        field("/spec/metrics/*/pods/metric", 23, 37, None, MergeStrategy::Object),
        field("/spec/metrics/*/pods/metric/name", 23, 37, None, MergeStrategy::Scalar),
        field(
            "/spec/metrics/*/pods/metric/selector",
            23,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/pods/metric/selector/matchExpressions",
            23,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/pods/metric/selector/matchExpressions/*",
            23,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/pods/metric/selector/matchExpressions/*/key",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/pods/metric/selector/matchExpressions/*/operator",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/pods/metric/selector/matchExpressions/*/values",
            23,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/pods/metric/selector/matchExpressions/*/values/*",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/pods/metric/selector/matchLabels",
            23,
            37,
            None,
            MergeStrategy::Map,
        ),
        field(
            "/spec/metrics/*/pods/metric/selector/matchLabels/*",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/pods/target", 23, 37, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/pods/target/averageUtilization",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/pods/target/averageValue",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/pods/target/type", 23, 37, None, MergeStrategy::Scalar),
        field("/spec/metrics/*/pods/target/value", 23, 37, None, MergeStrategy::Scalar),
        field("/spec/metrics/*/resource", 23, 37, None, MergeStrategy::Object),
        field("/spec/metrics/*/resource/name", 23, 37, None, MergeStrategy::Scalar),
        field("/spec/metrics/*/resource/target", 23, 37, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/resource/target/averageUtilization",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/resource/target/averageValue",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/resource/target/type",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/resource/target/value",
            23,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/type", 23, 37, None, MergeStrategy::Scalar),
        field("/spec/minReplicas", 23, 37, None, MergeStrategy::Scalar),
        field("/spec/scaleTargetRef", 23, 37, None, MergeStrategy::Object),
        field("/spec/scaleTargetRef/apiVersion", 23, 37, None, MergeStrategy::Scalar),
        field("/spec/scaleTargetRef/kind", 23, 37, None, MergeStrategy::Scalar),
        field("/spec/scaleTargetRef/name", 23, 37, None, MergeStrategy::Scalar),
    ]
});

static FIELDS_8: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 24, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 24, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 24, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 24, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            24,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 24, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 24, None, MergeStrategy::Scalar),
        field("/spec", 20, 37, None, MergeStrategy::Object),
        field("/spec/maxReplicas", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/metrics", 20, 24, None, MergeStrategy::AtomicList),
        field("/spec/metrics/*", 20, 24, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/containerResource",
            20,
            24,
            Some(FeatureGateId::HPAContainerMetrics),
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/containerResource/container",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/containerResource/name",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/containerResource/targetAverageUtilization",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/containerResource/targetAverageValue",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/external", 20, 24, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/external/metricName",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/metricSelector",
            20,
            24,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/external/metricSelector/matchExpressions",
            20,
            24,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/external/metricSelector/matchExpressions/*",
            20,
            24,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/external/metricSelector/matchExpressions/*/key",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/metricSelector/matchExpressions/*/operator",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/metricSelector/matchExpressions/*/values",
            20,
            24,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/external/metricSelector/matchExpressions/*/values/*",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/metricSelector/matchLabels",
            20,
            24,
            None,
            MergeStrategy::Map,
        ),
        field(
            "/spec/metrics/*/external/metricSelector/matchLabels/*",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/targetAverageValue",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/targetValue",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/object", 20, 24, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/object/averageValue",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/object/metricName", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/metrics/*/object/selector", 20, 24, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/object/selector/matchExpressions",
            20,
            24,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/object/selector/matchExpressions/*",
            20,
            24,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/object/selector/matchExpressions/*/key",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/selector/matchExpressions/*/operator",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/selector/matchExpressions/*/values",
            20,
            24,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/object/selector/matchExpressions/*/values/*",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/selector/matchLabels",
            20,
            24,
            None,
            MergeStrategy::Map,
        ),
        field(
            "/spec/metrics/*/object/selector/matchLabels/*",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/object/target", 20, 24, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/object/target/apiVersion",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/target/kind",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/target/name",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/targetValue",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/pods", 20, 24, None, MergeStrategy::Object),
        field("/spec/metrics/*/pods/metricName", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/metrics/*/pods/selector", 20, 24, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/pods/selector/matchExpressions",
            20,
            24,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/pods/selector/matchExpressions/*",
            20,
            24,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/pods/selector/matchExpressions/*/key",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/pods/selector/matchExpressions/*/operator",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/pods/selector/matchExpressions/*/values",
            20,
            24,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/pods/selector/matchExpressions/*/values/*",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/pods/selector/matchLabels",
            20,
            24,
            None,
            MergeStrategy::Map,
        ),
        field(
            "/spec/metrics/*/pods/selector/matchLabels/*",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/pods/targetAverageValue",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/resource", 20, 24, None, MergeStrategy::Object),
        field("/spec/metrics/*/resource/name", 20, 24, None, MergeStrategy::Scalar),
        field(
            "/spec/metrics/*/resource/targetAverageUtilization",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/resource/targetAverageValue",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/type", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/minReplicas", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/scaleTargetRef", 20, 24, None, MergeStrategy::Object),
        field("/spec/scaleTargetRef/apiVersion", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/scaleTargetRef/kind", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/scaleTargetRef/name", 20, 24, None, MergeStrategy::Scalar),
    ]
});

static FIELDS_9: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 25, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 25, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 25, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 25, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 25, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 25, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 25, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 25, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 25, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            25,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 25, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 25, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 25, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 25, None, MergeStrategy::Scalar),
        field("/spec", 20, 37, None, MergeStrategy::Object),
        field("/spec/behavior", 20, 25, None, MergeStrategy::Object),
        field("/spec/behavior/scaleDown", 20, 25, None, MergeStrategy::Object),
        field(
            "/spec/behavior/scaleDown/policies",
            20,
            25,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/behavior/scaleDown/policies/*",
            20,
            25,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/behavior/scaleDown/policies/*/periodSeconds",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/behavior/scaleDown/policies/*/type",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/behavior/scaleDown/policies/*/value",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/behavior/scaleDown/selectPolicy",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/behavior/scaleDown/stabilizationWindowSeconds",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/behavior/scaleUp", 20, 25, None, MergeStrategy::Object),
        field(
            "/spec/behavior/scaleUp/policies",
            20,
            25,
            None,
            MergeStrategy::AtomicList,
        ),
        field("/spec/behavior/scaleUp/policies/*", 20, 25, None, MergeStrategy::Object),
        field(
            "/spec/behavior/scaleUp/policies/*/periodSeconds",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/behavior/scaleUp/policies/*/type",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/behavior/scaleUp/policies/*/value",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/behavior/scaleUp/selectPolicy",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/behavior/scaleUp/stabilizationWindowSeconds",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/maxReplicas", 20, 25, None, MergeStrategy::Scalar),
        field("/spec/metrics", 20, 25, None, MergeStrategy::AtomicList),
        field("/spec/metrics/*", 20, 25, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/containerResource",
            20,
            25,
            Some(FeatureGateId::HPAContainerMetrics),
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/containerResource/container",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/containerResource/name",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/containerResource/target",
            20,
            25,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/containerResource/target/averageUtilization",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/containerResource/target/averageValue",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/containerResource/target/type",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/containerResource/target/value",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/external", 20, 25, None, MergeStrategy::Object),
        field("/spec/metrics/*/external/metric", 20, 25, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/external/metric/name",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/metric/selector",
            20,
            25,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/external/metric/selector/matchExpressions",
            20,
            25,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/external/metric/selector/matchExpressions/*",
            20,
            25,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/external/metric/selector/matchExpressions/*/key",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/metric/selector/matchExpressions/*/operator",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/metric/selector/matchExpressions/*/values",
            20,
            25,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/external/metric/selector/matchExpressions/*/values/*",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/metric/selector/matchLabels",
            20,
            25,
            None,
            MergeStrategy::Map,
        ),
        field(
            "/spec/metrics/*/external/metric/selector/matchLabels/*",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/external/target", 20, 25, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/external/target/averageUtilization",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/target/averageValue",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/target/type",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/external/target/value",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/object", 20, 25, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/object/describedObject",
            20,
            25,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/object/describedObject/apiVersion",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/describedObject/kind",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/describedObject/name",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/object/metric", 20, 25, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/object/metric/name",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/metric/selector",
            20,
            25,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/object/metric/selector/matchExpressions",
            20,
            25,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/object/metric/selector/matchExpressions/*",
            20,
            25,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/object/metric/selector/matchExpressions/*/key",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/metric/selector/matchExpressions/*/operator",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/metric/selector/matchExpressions/*/values",
            20,
            25,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/object/metric/selector/matchExpressions/*/values/*",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/metric/selector/matchLabels",
            20,
            25,
            None,
            MergeStrategy::Map,
        ),
        field(
            "/spec/metrics/*/object/metric/selector/matchLabels/*",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/object/target", 20, 25, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/object/target/averageUtilization",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/target/averageValue",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/target/type",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/object/target/value",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/pods", 20, 25, None, MergeStrategy::Object),
        field("/spec/metrics/*/pods/metric", 20, 25, None, MergeStrategy::Object),
        field("/spec/metrics/*/pods/metric/name", 20, 25, None, MergeStrategy::Scalar),
        field(
            "/spec/metrics/*/pods/metric/selector",
            20,
            25,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/pods/metric/selector/matchExpressions",
            20,
            25,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/pods/metric/selector/matchExpressions/*",
            20,
            25,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/metrics/*/pods/metric/selector/matchExpressions/*/key",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/pods/metric/selector/matchExpressions/*/operator",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/pods/metric/selector/matchExpressions/*/values",
            20,
            25,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/metrics/*/pods/metric/selector/matchExpressions/*/values/*",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/pods/metric/selector/matchLabels",
            20,
            25,
            None,
            MergeStrategy::Map,
        ),
        field(
            "/spec/metrics/*/pods/metric/selector/matchLabels/*",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/pods/target", 20, 25, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/pods/target/averageUtilization",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/pods/target/averageValue",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/pods/target/type", 20, 25, None, MergeStrategy::Scalar),
        field("/spec/metrics/*/pods/target/value", 20, 25, None, MergeStrategy::Scalar),
        field("/spec/metrics/*/resource", 20, 25, None, MergeStrategy::Object),
        field("/spec/metrics/*/resource/name", 20, 25, None, MergeStrategy::Scalar),
        field("/spec/metrics/*/resource/target", 20, 25, None, MergeStrategy::Object),
        field(
            "/spec/metrics/*/resource/target/averageUtilization",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/resource/target/averageValue",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/resource/target/type",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/metrics/*/resource/target/value",
            20,
            25,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/metrics/*/type", 20, 25, None, MergeStrategy::Scalar),
        field("/spec/minReplicas", 20, 25, None, MergeStrategy::Scalar),
        field("/spec/scaleTargetRef", 20, 25, None, MergeStrategy::Object),
        field("/spec/scaleTargetRef/apiVersion", 20, 25, None, MergeStrategy::Scalar),
        field("/spec/scaleTargetRef/kind", 20, 25, None, MergeStrategy::Scalar),
        field("/spec/scaleTargetRef/name", 20, 25, None, MergeStrategy::Scalar),
    ]
});

static FIELDS_10: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 21, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 21, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 21, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 21, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 21, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 21, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 21, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 21, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 21, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            21,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 21, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            21,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            21,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            21,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 21, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 21, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 21, 37, None, MergeStrategy::Scalar),
        field("/spec", 20, 37, None, MergeStrategy::Object),
        field("/spec/maxUnavailable", 21, 37, None, MergeStrategy::Scalar),
        field("/spec/minAvailable", 21, 37, None, MergeStrategy::Scalar),
        field("/spec/selector", 21, 37, None, MergeStrategy::Object),
        field(
            "/spec/selector/matchExpressions",
            21,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field("/spec/selector/matchExpressions/*", 21, 37, None, MergeStrategy::Object),
        field(
            "/spec/selector/matchExpressions/*/key",
            21,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/selector/matchExpressions/*/operator",
            21,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/selector/matchExpressions/*/values",
            21,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/selector/matchExpressions/*/values/*",
            21,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/selector/matchLabels", 21, 37, None, MergeStrategy::Map),
        field("/spec/selector/matchLabels/*", 21, 37, None, MergeStrategy::Scalar),
        field(
            "/spec/unhealthyPodEvictionPolicy",
            26,
            37,
            Some(FeatureGateId::PDBUnhealthyPodEvictionPolicy),
            MergeStrategy::Scalar,
        ),
    ]
});

static FIELDS_11: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 24, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 24, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 24, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 24, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            24,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 24, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 24, None, MergeStrategy::Scalar),
        field("/spec", 20, 37, None, MergeStrategy::Object),
        field("/spec/maxUnavailable", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/minAvailable", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/selector", 20, 24, None, MergeStrategy::Object),
        field(
            "/spec/selector/matchExpressions",
            20,
            24,
            None,
            MergeStrategy::AtomicList,
        ),
        field("/spec/selector/matchExpressions/*", 20, 24, None, MergeStrategy::Object),
        field(
            "/spec/selector/matchExpressions/*/key",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/selector/matchExpressions/*/operator",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/selector/matchExpressions/*/values",
            20,
            24,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/selector/matchExpressions/*/values/*",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/selector/matchLabels", 20, 24, None, MergeStrategy::Map),
        field("/spec/selector/matchLabels/*", 20, 24, None, MergeStrategy::Scalar),
    ]
});

static FIELDS_12: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 37, None, MergeStrategy::Scalar),
        field("/spec", 20, 37, None, MergeStrategy::Object),
        field("/spec/hard", 20, 37, None, MergeStrategy::Map),
        field("/spec/hard/*", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/scopeSelector", 20, 37, None, MergeStrategy::Object),
        field(
            "/spec/scopeSelector/matchExpressions",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/scopeSelector/matchExpressions/*",
            20,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/scopeSelector/matchExpressions/*/operator",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/scopeSelector/matchExpressions/*/scopeName",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/scopeSelector/matchExpressions/*/values",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/scopeSelector/matchExpressions/*/values/*",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/scopes", 20, 37, None, MergeStrategy::AtomicList),
        field("/spec/scopes/*", 20, 37, None, MergeStrategy::Scalar),
    ]
});

static FIELDS_13: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 37, None, MergeStrategy::Scalar),
        field("/spec", 20, 37, None, MergeStrategy::Object),
        field("/spec/limits", 20, 37, None, MergeStrategy::AtomicList),
        field("/spec/limits/*", 20, 37, None, MergeStrategy::Object),
        field("/spec/limits/*/default", 20, 37, None, MergeStrategy::Map),
        field("/spec/limits/*/default/*", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/limits/*/defaultRequest", 20, 37, None, MergeStrategy::Map),
        field("/spec/limits/*/defaultRequest/*", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/limits/*/max", 20, 37, None, MergeStrategy::Map),
        field("/spec/limits/*/max/*", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/limits/*/maxLimitRequestRatio", 20, 37, None, MergeStrategy::Map),
        field(
            "/spec/limits/*/maxLimitRequestRatio/*",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/limits/*/min", 20, 37, None, MergeStrategy::Map),
        field("/spec/limits/*/min/*", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/limits/*/type", 20, 37, None, MergeStrategy::Scalar),
    ]
});

static FIELDS_14: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/description", 20, 37, None, MergeStrategy::Scalar),
        field("/globalDefault", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/preemptionPolicy",
            20,
            37,
            Some(FeatureGateId::NonPreemptingPriority),
            MergeStrategy::Scalar,
        ),
        field("/value", 20, 37, None, MergeStrategy::Scalar),
    ]
});

static FIELDS_15: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/handler", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/overhead",
            20,
            37,
            Some(FeatureGateId::PodOverhead),
            MergeStrategy::Object,
        ),
        field("/overhead/podFixed", 20, 37, None, MergeStrategy::Map),
        field("/overhead/podFixed/*", 20, 37, None, MergeStrategy::Scalar),
        field("/scheduling", 20, 37, None, MergeStrategy::Object),
        field("/scheduling/nodeSelector", 20, 37, None, MergeStrategy::Map),
        field("/scheduling/nodeSelector/*", 20, 37, None, MergeStrategy::Scalar),
        field("/scheduling/tolerations", 20, 37, None, MergeStrategy::AtomicList),
        field("/scheduling/tolerations/*", 20, 37, None, MergeStrategy::Object),
        field("/scheduling/tolerations/*/effect", 20, 37, None, MergeStrategy::Scalar),
        field("/scheduling/tolerations/*/key", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/scheduling/tolerations/*/operator",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/scheduling/tolerations/*/tolerationSeconds",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/scheduling/tolerations/*/value", 20, 37, None, MergeStrategy::Scalar),
    ]
});

static FIELDS_16: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/handler", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 24, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 24, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 24, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 24, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            24,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 24, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 24, None, MergeStrategy::Scalar),
        field(
            "/overhead",
            20,
            24,
            Some(FeatureGateId::PodOverhead),
            MergeStrategy::Object,
        ),
        field("/overhead/podFixed", 20, 24, None, MergeStrategy::Map),
        field("/overhead/podFixed/*", 20, 24, None, MergeStrategy::Scalar),
        field("/scheduling", 20, 24, None, MergeStrategy::Object),
        field("/scheduling/nodeSelector", 20, 24, None, MergeStrategy::Map),
        field("/scheduling/nodeSelector/*", 20, 24, None, MergeStrategy::Scalar),
        field("/scheduling/tolerations", 20, 24, None, MergeStrategy::AtomicList),
        field("/scheduling/tolerations/*", 20, 24, None, MergeStrategy::Object),
        field("/scheduling/tolerations/*/effect", 20, 24, None, MergeStrategy::Scalar),
        field("/scheduling/tolerations/*/key", 20, 24, None, MergeStrategy::Scalar),
        field(
            "/scheduling/tolerations/*/operator",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/scheduling/tolerations/*/tolerationSeconds",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/scheduling/tolerations/*/value", 20, 24, None, MergeStrategy::Scalar),
    ]
});

static FIELDS_17: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 24, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 24, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 24, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 24, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            24,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 24, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 24, None, MergeStrategy::Scalar),
        field("/spec", 20, 24, None, MergeStrategy::Object),
        field("/spec/allowPrivilegeEscalation", 20, 24, None, MergeStrategy::Scalar),
        field(
            "/spec/allowedCSIDrivers",
            20,
            24,
            Some(FeatureGateId::CSIInlineVolume),
            MergeStrategy::AtomicList,
        ),
        field("/spec/allowedCSIDrivers/*", 20, 24, None, MergeStrategy::Object),
        field("/spec/allowedCSIDrivers/*/name", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/allowedCapabilities", 20, 24, None, MergeStrategy::AtomicList),
        field("/spec/allowedCapabilities/*", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/allowedFlexVolumes", 20, 24, None, MergeStrategy::AtomicList),
        field("/spec/allowedFlexVolumes/*", 20, 24, None, MergeStrategy::Object),
        field("/spec/allowedFlexVolumes/*/driver", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/allowedHostPaths", 20, 24, None, MergeStrategy::AtomicList),
        field("/spec/allowedHostPaths/*", 20, 24, None, MergeStrategy::Object),
        field(
            "/spec/allowedHostPaths/*/pathPrefix",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/allowedHostPaths/*/readOnly", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/allowedProcMountTypes", 20, 24, None, MergeStrategy::AtomicList),
        field("/spec/allowedProcMountTypes/*", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/allowedUnsafeSysctls", 20, 24, None, MergeStrategy::AtomicList),
        field("/spec/allowedUnsafeSysctls/*", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/defaultAddCapabilities", 20, 24, None, MergeStrategy::AtomicList),
        field("/spec/defaultAddCapabilities/*", 20, 24, None, MergeStrategy::Scalar),
        field(
            "/spec/defaultAllowPrivilegeEscalation",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/forbiddenSysctls", 20, 24, None, MergeStrategy::AtomicList),
        field("/spec/forbiddenSysctls/*", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/fsGroup", 20, 24, None, MergeStrategy::Object),
        field("/spec/fsGroup/ranges", 20, 24, None, MergeStrategy::AtomicList),
        field("/spec/fsGroup/ranges/*", 20, 24, None, MergeStrategy::Object),
        field("/spec/fsGroup/ranges/*/max", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/fsGroup/ranges/*/min", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/fsGroup/rule", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/hostIPC", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/hostNetwork", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/hostPID", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/hostPorts", 20, 24, None, MergeStrategy::AtomicList),
        field("/spec/hostPorts/*", 20, 24, None, MergeStrategy::Object),
        field("/spec/hostPorts/*/max", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/hostPorts/*/min", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/privileged", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/readOnlyRootFilesystem", 20, 24, None, MergeStrategy::Scalar),
        field(
            "/spec/requiredDropCapabilities",
            20,
            24,
            None,
            MergeStrategy::AtomicList,
        ),
        field("/spec/requiredDropCapabilities/*", 20, 24, None, MergeStrategy::Scalar),
        field(
            "/spec/runAsGroup",
            20,
            24,
            Some(FeatureGateId::RunAsGroup),
            MergeStrategy::Object,
        ),
        field("/spec/runAsGroup/ranges", 20, 24, None, MergeStrategy::AtomicList),
        field("/spec/runAsGroup/ranges/*", 20, 24, None, MergeStrategy::Object),
        field("/spec/runAsGroup/ranges/*/max", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/runAsGroup/ranges/*/min", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/runAsGroup/rule", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/runAsUser", 20, 24, None, MergeStrategy::Object),
        field("/spec/runAsUser/ranges", 20, 24, None, MergeStrategy::AtomicList),
        field("/spec/runAsUser/ranges/*", 20, 24, None, MergeStrategy::Object),
        field("/spec/runAsUser/ranges/*/max", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/runAsUser/ranges/*/min", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/runAsUser/rule", 20, 24, None, MergeStrategy::Scalar),
        field(
            "/spec/runtimeClass",
            20,
            24,
            Some(FeatureGateId::RuntimeClass),
            MergeStrategy::Object,
        ),
        field(
            "/spec/runtimeClass/allowedRuntimeClassNames",
            20,
            24,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/runtimeClass/allowedRuntimeClassNames/*",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/runtimeClass/defaultRuntimeClassName",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/seLinux", 20, 24, None, MergeStrategy::Object),
        field("/spec/seLinux/rule", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/seLinux/seLinuxOptions", 20, 24, None, MergeStrategy::Object),
        field(
            "/spec/seLinux/seLinuxOptions/level",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/seLinux/seLinuxOptions/role", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/seLinux/seLinuxOptions/type", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/seLinux/seLinuxOptions/user", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/supplementalGroups", 20, 24, None, MergeStrategy::Object),
        field(
            "/spec/supplementalGroups/ranges",
            20,
            24,
            None,
            MergeStrategy::AtomicList,
        ),
        field("/spec/supplementalGroups/ranges/*", 20, 24, None, MergeStrategy::Object),
        field(
            "/spec/supplementalGroups/ranges/*/max",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/supplementalGroups/ranges/*/min",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/supplementalGroups/rule", 20, 24, None, MergeStrategy::Scalar),
        field("/spec/volumes", 20, 24, None, MergeStrategy::AtomicList),
        field("/spec/volumes/*", 20, 24, None, MergeStrategy::Scalar),
    ]
});

pub(super) fn for_api(gvk: GroupVersionKind) -> Result<KindCapability, Finding> {
    let (fields, scope, first, last) = match (gvk.kind.as_str(), gvk.api_version().as_str()) {
        ("Namespace", "v1") => (FIELDS_0.as_slice(), ResourceScope::Cluster, 20, 37),
        ("ServiceAccount", "v1") => (FIELDS_1.as_slice(), ResourceScope::Namespaced, 20, 37),
        ("Role", "rbac.authorization.k8s.io/v1") => (FIELDS_2.as_slice(), ResourceScope::Namespaced, 20, 37),
        ("RoleBinding", "rbac.authorization.k8s.io/v1") => (FIELDS_3.as_slice(), ResourceScope::Namespaced, 20, 37),
        ("ClusterRole", "rbac.authorization.k8s.io/v1") => (FIELDS_4.as_slice(), ResourceScope::Cluster, 20, 37),
        ("ClusterRoleBinding", "rbac.authorization.k8s.io/v1") => (FIELDS_5.as_slice(), ResourceScope::Cluster, 20, 37),
        ("HorizontalPodAutoscaler", "autoscaling/v1") => (FIELDS_6.as_slice(), ResourceScope::Namespaced, 20, 37),
        ("HorizontalPodAutoscaler", "autoscaling/v2") => (FIELDS_7.as_slice(), ResourceScope::Namespaced, 23, 37),
        ("HorizontalPodAutoscaler", "autoscaling/v2beta1") => (FIELDS_8.as_slice(), ResourceScope::Namespaced, 20, 24),
        ("HorizontalPodAutoscaler", "autoscaling/v2beta2") => (FIELDS_9.as_slice(), ResourceScope::Namespaced, 20, 25),
        ("PodDisruptionBudget", "policy/v1") => (FIELDS_10.as_slice(), ResourceScope::Namespaced, 21, 37),
        ("PodDisruptionBudget", "policy/v1beta1") => (FIELDS_11.as_slice(), ResourceScope::Namespaced, 20, 24),
        ("ResourceQuota", "v1") => (FIELDS_12.as_slice(), ResourceScope::Namespaced, 20, 37),
        ("LimitRange", "v1") => (FIELDS_13.as_slice(), ResourceScope::Namespaced, 20, 37),
        ("PriorityClass", "scheduling.k8s.io/v1") => (FIELDS_14.as_slice(), ResourceScope::Cluster, 20, 37),
        ("RuntimeClass", "node.k8s.io/v1") => (FIELDS_15.as_slice(), ResourceScope::Cluster, 20, 37),
        ("RuntimeClass", "node.k8s.io/v1beta1") => (FIELDS_16.as_slice(), ResourceScope::Cluster, 20, 24),
        ("PodSecurityPolicy", "policy/v1beta1") => (FIELDS_17.as_slice(), ResourceScope::Cluster, 20, 24),
        _ => return Err(Finding::error(FindingCode::InvalidRegistration, Phase::Decoding)),
    };
    Ok(KindCapability {
        gvk,
        scope,
        api_since: version(first),
        api_removed: (last < 37).then(|| version(last + 1)),
        fields,
    })
}
