//! Finite reviewed networking field/version/merge declarations.
use crate::{
    capability::{FeatureGateId, FieldAdmission, FieldCapability, KindCapability, KubernetesVersion, MergeStrategy},
    diagnostic::{Finding, FindingCode, Phase},
    model::{GroupVersionKind, ResourceScope},
};
use std::sync::LazyLock;
fn version(minor: u8) -> KubernetesVersion {
    KubernetesVersion::new(1, minor).unwrap_or(KubernetesVersion::MAX)
}
fn field(
    path: &'static str,
    first: u8,
    last: u8,
    gate: Option<FeatureGateId>,
    merge: MergeStrategy,
) -> FieldCapability {
    FieldCapability {
        path,
        since: version(first),
        removed: (last < 37).then(|| version(last + 1)),
        deprecated: None,
        feature_gate: gate,
        admission: if path.ends_with("/deprecatedTopology") {
            FieldAdmission::PreserveOnly
        } else {
            FieldAdmission::Typed
        },
        merge,
        semantic_note: if path.ends_with("/deprecatedTopology") {
            Some("Server-owned topology is retained; desired writes are ignored by the native API.")
        } else {
            None
        },
    }
}
static FIELDS_0: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 37, None, MergeStrategy::Scalar),
        field("/spec", 20, 37, None, MergeStrategy::Object),
        field(
            "/spec/allocateLoadBalancerNodePorts",
            24,
            37,
            Some(FeatureGateId::ServiceLBNodePortControl),
            MergeStrategy::Scalar,
        ),
        field("/spec/clusterIP", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/spec/clusterIPs",
            23,
            37,
            Some(FeatureGateId::IPv6DualStack),
            MergeStrategy::AtomicList,
        ),
        field("/spec/clusterIPs/*", 23, 37, None, MergeStrategy::Scalar),
        field("/spec/externalIPs", 20, 37, None, MergeStrategy::AtomicList),
        field("/spec/externalIPs/*", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/externalName", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/externalTrafficPolicy", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/healthCheckNodePort", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/spec/internalTrafficPolicy",
            26,
            37,
            Some(FeatureGateId::ServiceInternalTrafficPolicy),
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/ipFamilies",
            23,
            37,
            Some(FeatureGateId::IPv6DualStack),
            MergeStrategy::AtomicList,
        ),
        field("/spec/ipFamilies/*", 23, 37, None, MergeStrategy::Scalar),
        field(
            "/spec/ipFamilyPolicy",
            23,
            37,
            Some(FeatureGateId::IPv6DualStack),
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/loadBalancerClass",
            24,
            37,
            Some(FeatureGateId::ServiceLoadBalancerClass),
            MergeStrategy::Scalar,
        ),
        field("/spec/loadBalancerIP", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/spec/loadBalancerSourceRanges",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field("/spec/loadBalancerSourceRanges/*", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/spec/ports",
            20,
            37,
            None,
            MergeStrategy::MapList {
                keys: &["port", "protocol"],
            },
        ),
        field("/spec/ports/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/spec/ports/*/appProtocol",
            20,
            37,
            Some(FeatureGateId::ServiceAppProtocol),
            MergeStrategy::Scalar,
        ),
        field("/spec/ports/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/ports/*/nodePort", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/ports/*/port", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/ports/*/protocol", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/ports/*/targetPort", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/publishNotReadyAddresses", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/selector", 20, 37, None, MergeStrategy::Map),
        field("/spec/selector/*", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/sessionAffinity", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/sessionAffinityConfig", 20, 37, None, MergeStrategy::Object),
        field(
            "/spec/sessionAffinityConfig/clientIP",
            20,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/sessionAffinityConfig/clientIP/timeoutSeconds",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/trafficDistribution",
            33,
            37,
            Some(FeatureGateId::ServiceTrafficDistribution),
            MergeStrategy::Scalar,
        ),
        field("/spec/type", 20, 37, None, MergeStrategy::Scalar),
    ]
});
static FIELDS_1: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 37, None, MergeStrategy::Scalar),
        field("/subsets", 20, 37, None, MergeStrategy::AtomicList),
        field("/subsets/*", 20, 37, None, MergeStrategy::Object),
        field("/subsets/*/addresses", 20, 37, None, MergeStrategy::AtomicList),
        field("/subsets/*/addresses/*", 20, 37, None, MergeStrategy::Object),
        field("/subsets/*/addresses/*/hostname", 20, 37, None, MergeStrategy::Scalar),
        field("/subsets/*/addresses/*/ip", 20, 37, None, MergeStrategy::Scalar),
        field("/subsets/*/addresses/*/nodeName", 20, 37, None, MergeStrategy::Scalar),
        field("/subsets/*/addresses/*/targetRef", 20, 37, None, MergeStrategy::Object),
        field(
            "/subsets/*/addresses/*/targetRef/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/subsets/*/addresses/*/targetRef/fieldPath",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/subsets/*/addresses/*/targetRef/kind",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/subsets/*/addresses/*/targetRef/name",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/subsets/*/addresses/*/targetRef/namespace",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/subsets/*/addresses/*/targetRef/resourceVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/subsets/*/addresses/*/targetRef/uid",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/subsets/*/notReadyAddresses", 20, 37, None, MergeStrategy::AtomicList),
        field("/subsets/*/notReadyAddresses/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/subsets/*/notReadyAddresses/*/hostname",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/subsets/*/notReadyAddresses/*/ip", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/subsets/*/notReadyAddresses/*/nodeName",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/subsets/*/notReadyAddresses/*/targetRef",
            20,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/subsets/*/notReadyAddresses/*/targetRef/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/subsets/*/notReadyAddresses/*/targetRef/fieldPath",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/subsets/*/notReadyAddresses/*/targetRef/kind",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/subsets/*/notReadyAddresses/*/targetRef/name",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/subsets/*/notReadyAddresses/*/targetRef/namespace",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/subsets/*/notReadyAddresses/*/targetRef/resourceVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/subsets/*/notReadyAddresses/*/targetRef/uid",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/subsets/*/ports", 20, 37, None, MergeStrategy::AtomicList),
        field("/subsets/*/ports/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/subsets/*/ports/*/appProtocol",
            20,
            37,
            Some(FeatureGateId::ServiceAppProtocol),
            MergeStrategy::Scalar,
        ),
        field("/subsets/*/ports/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/subsets/*/ports/*/port", 20, 37, None, MergeStrategy::Scalar),
        field("/subsets/*/ports/*/protocol", 20, 37, None, MergeStrategy::Scalar),
    ]
});
static FIELDS_2: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/addressType", 21, 37, None, MergeStrategy::Scalar),
        field("/endpoints", 21, 37, None, MergeStrategy::AtomicList),
        field("/endpoints/*", 21, 37, None, MergeStrategy::Object),
        field("/endpoints/*/addresses", 21, 37, None, MergeStrategy::SetList),
        field("/endpoints/*/addresses/*", 21, 37, None, MergeStrategy::Scalar),
        field("/endpoints/*/conditions", 21, 37, None, MergeStrategy::Object),
        field("/endpoints/*/conditions/ready", 21, 37, None, MergeStrategy::Scalar),
        field(
            "/endpoints/*/conditions/serving",
            26,
            37,
            Some(FeatureGateId::EndpointSliceTerminatingCondition),
            MergeStrategy::Scalar,
        ),
        field(
            "/endpoints/*/conditions/terminating",
            26,
            37,
            Some(FeatureGateId::EndpointSliceTerminatingCondition),
            MergeStrategy::Scalar,
        ),
        field("/endpoints/*/deprecatedTopology", 21, 37, None, MergeStrategy::Map),
        field("/endpoints/*/deprecatedTopology/*", 21, 37, None, MergeStrategy::Scalar),
        field("/endpoints/*/hostname", 21, 37, None, MergeStrategy::Scalar),
        field(
            "/endpoints/*/nodeName",
            21,
            37,
            Some(FeatureGateId::EndpointSliceNodeName),
            MergeStrategy::Scalar,
        ),
        field("/endpoints/*/targetRef", 21, 37, None, MergeStrategy::Object),
        field("/endpoints/*/targetRef/apiVersion", 21, 37, None, MergeStrategy::Scalar),
        field("/endpoints/*/targetRef/fieldPath", 21, 37, None, MergeStrategy::Scalar),
        field("/endpoints/*/targetRef/kind", 21, 37, None, MergeStrategy::Scalar),
        field("/endpoints/*/targetRef/name", 21, 37, None, MergeStrategy::Scalar),
        field("/endpoints/*/targetRef/namespace", 21, 37, None, MergeStrategy::Scalar),
        field(
            "/endpoints/*/targetRef/resourceVersion",
            21,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/endpoints/*/targetRef/uid", 21, 37, None, MergeStrategy::Scalar),
        field("/endpoints/*/zone", 21, 37, None, MergeStrategy::Scalar),
        field("/metadata", 21, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 21, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 21, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 21, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 21, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 21, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 21, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 21, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 21, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 21, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            21,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 21, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            21,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            21,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            21,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 21, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 21, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 21, 37, None, MergeStrategy::Scalar),
        field("/ports", 21, 37, None, MergeStrategy::AtomicList),
        field("/ports/*", 21, 37, None, MergeStrategy::Object),
        field(
            "/ports/*/appProtocol",
            21,
            37,
            Some(FeatureGateId::ServiceAppProtocol),
            MergeStrategy::Scalar,
        ),
        field("/ports/*/name", 21, 37, None, MergeStrategy::Scalar),
        field("/ports/*/port", 21, 37, None, MergeStrategy::Scalar),
        field("/ports/*/protocol", 21, 37, None, MergeStrategy::Scalar),
    ]
});
static FIELDS_3: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/addressType", 20, 24, None, MergeStrategy::Scalar),
        field("/endpoints", 20, 24, None, MergeStrategy::AtomicList),
        field("/endpoints/*", 20, 24, None, MergeStrategy::Object),
        field("/endpoints/*/addresses", 20, 24, None, MergeStrategy::SetList),
        field("/endpoints/*/addresses/*", 20, 24, None, MergeStrategy::Scalar),
        field("/endpoints/*/conditions", 20, 24, None, MergeStrategy::Object),
        field("/endpoints/*/conditions/ready", 20, 24, None, MergeStrategy::Scalar),
        field(
            "/endpoints/*/conditions/serving",
            26,
            24,
            Some(FeatureGateId::EndpointSliceTerminatingCondition),
            MergeStrategy::Scalar,
        ),
        field(
            "/endpoints/*/conditions/terminating",
            26,
            24,
            Some(FeatureGateId::EndpointSliceTerminatingCondition),
            MergeStrategy::Scalar,
        ),
        field("/endpoints/*/hostname", 20, 24, None, MergeStrategy::Scalar),
        field(
            "/endpoints/*/nodeName",
            21,
            24,
            Some(FeatureGateId::EndpointSliceNodeName),
            MergeStrategy::Scalar,
        ),
        field("/endpoints/*/targetRef", 20, 24, None, MergeStrategy::Object),
        field("/endpoints/*/targetRef/apiVersion", 20, 24, None, MergeStrategy::Scalar),
        field("/endpoints/*/targetRef/fieldPath", 20, 24, None, MergeStrategy::Scalar),
        field("/endpoints/*/targetRef/kind", 20, 24, None, MergeStrategy::Scalar),
        field("/endpoints/*/targetRef/name", 20, 24, None, MergeStrategy::Scalar),
        field("/endpoints/*/targetRef/namespace", 20, 24, None, MergeStrategy::Scalar),
        field(
            "/endpoints/*/targetRef/resourceVersion",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/endpoints/*/targetRef/uid", 20, 24, None, MergeStrategy::Scalar),
        field("/endpoints/*/topology", 20, 24, None, MergeStrategy::Map),
        field("/endpoints/*/topology/*", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata", 20, 24, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 24, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 24, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 24, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 24, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            24,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 24, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            24,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 24, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 24, None, MergeStrategy::Scalar),
        field("/ports", 20, 24, None, MergeStrategy::AtomicList),
        field("/ports/*", 20, 24, None, MergeStrategy::Object),
        field(
            "/ports/*/appProtocol",
            20,
            24,
            Some(FeatureGateId::ServiceAppProtocol),
            MergeStrategy::Scalar,
        ),
        field("/ports/*/name", 20, 24, None, MergeStrategy::Scalar),
        field("/ports/*/port", 20, 24, None, MergeStrategy::Scalar),
        field("/ports/*/protocol", 20, 24, None, MergeStrategy::Scalar),
    ]
});
static FIELDS_4: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 21, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 21, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 21, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 21, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 21, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            21,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 21, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 21, None, MergeStrategy::Scalar),
        field("/spec", 20, 21, None, MergeStrategy::Object),
        field("/spec/backend", 20, 21, None, MergeStrategy::Object),
        field("/spec/backend/resource", 20, 21, None, MergeStrategy::Object),
        field("/spec/backend/resource/apiGroup", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/backend/resource/kind", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/backend/resource/name", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/backend/serviceName", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/backend/servicePort", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/ingressClassName", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/rules", 20, 21, None, MergeStrategy::AtomicList),
        field("/spec/rules/*", 20, 21, None, MergeStrategy::Object),
        field("/spec/rules/*/host", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/rules/*/http", 20, 21, None, MergeStrategy::Object),
        field("/spec/rules/*/http/paths", 20, 21, None, MergeStrategy::AtomicList),
        field("/spec/rules/*/http/paths/*", 20, 21, None, MergeStrategy::Object),
        field(
            "/spec/rules/*/http/paths/*/backend",
            20,
            21,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/resource",
            20,
            21,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/resource/apiGroup",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/resource/kind",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/resource/name",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/serviceName",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/servicePort",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/rules/*/http/paths/*/path", 20, 21, None, MergeStrategy::Scalar),
        field(
            "/spec/rules/*/http/paths/*/pathType",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/tls", 20, 21, None, MergeStrategy::AtomicList),
        field("/spec/tls/*", 20, 21, None, MergeStrategy::Object),
        field("/spec/tls/*/hosts", 20, 21, None, MergeStrategy::AtomicList),
        field("/spec/tls/*/hosts/*", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/tls/*/secretName", 20, 21, None, MergeStrategy::Scalar),
    ]
});
static FIELDS_5: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 37, None, MergeStrategy::Scalar),
        field("/spec", 20, 37, None, MergeStrategy::Object),
        field("/spec/defaultBackend", 20, 37, None, MergeStrategy::Object),
        field("/spec/defaultBackend/resource", 20, 37, None, MergeStrategy::Object),
        field(
            "/spec/defaultBackend/resource/apiGroup",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/defaultBackend/resource/kind",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/defaultBackend/resource/name",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/defaultBackend/service", 20, 37, None, MergeStrategy::Object),
        field("/spec/defaultBackend/service/name", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/defaultBackend/service/port", 20, 37, None, MergeStrategy::Object),
        field(
            "/spec/defaultBackend/service/port/name",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/defaultBackend/service/port/number",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/ingressClassName", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/rules", 20, 37, None, MergeStrategy::AtomicList),
        field("/spec/rules/*", 20, 37, None, MergeStrategy::Object),
        field("/spec/rules/*/host", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/rules/*/http", 20, 37, None, MergeStrategy::Object),
        field("/spec/rules/*/http/paths", 20, 37, None, MergeStrategy::AtomicList),
        field("/spec/rules/*/http/paths/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/spec/rules/*/http/paths/*/backend",
            20,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/resource",
            20,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/resource/apiGroup",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/resource/kind",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/resource/name",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/service",
            20,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/service/name",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/service/port",
            20,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/service/port/name",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/service/port/number",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/rules/*/http/paths/*/path", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/spec/rules/*/http/paths/*/pathType",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/tls", 20, 37, None, MergeStrategy::AtomicList),
        field("/spec/tls/*", 20, 37, None, MergeStrategy::Object),
        field("/spec/tls/*/hosts", 20, 37, None, MergeStrategy::AtomicList),
        field("/spec/tls/*/hosts/*", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/tls/*/secretName", 20, 37, None, MergeStrategy::Scalar),
    ]
});
static FIELDS_6: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 21, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 21, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 21, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 21, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 21, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            21,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 21, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 21, None, MergeStrategy::Scalar),
        field("/spec", 20, 21, None, MergeStrategy::Object),
        field("/spec/backend", 20, 21, None, MergeStrategy::Object),
        field("/spec/backend/resource", 20, 21, None, MergeStrategy::Object),
        field("/spec/backend/resource/apiGroup", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/backend/resource/kind", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/backend/resource/name", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/backend/serviceName", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/backend/servicePort", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/ingressClassName", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/rules", 20, 21, None, MergeStrategy::AtomicList),
        field("/spec/rules/*", 20, 21, None, MergeStrategy::Object),
        field("/spec/rules/*/host", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/rules/*/http", 20, 21, None, MergeStrategy::Object),
        field("/spec/rules/*/http/paths", 20, 21, None, MergeStrategy::AtomicList),
        field("/spec/rules/*/http/paths/*", 20, 21, None, MergeStrategy::Object),
        field(
            "/spec/rules/*/http/paths/*/backend",
            20,
            21,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/resource",
            20,
            21,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/resource/apiGroup",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/resource/kind",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/resource/name",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/serviceName",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/rules/*/http/paths/*/backend/servicePort",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/rules/*/http/paths/*/path", 20, 21, None, MergeStrategy::Scalar),
        field(
            "/spec/rules/*/http/paths/*/pathType",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/tls", 20, 21, None, MergeStrategy::AtomicList),
        field("/spec/tls/*", 20, 21, None, MergeStrategy::Object),
        field("/spec/tls/*/hosts", 20, 21, None, MergeStrategy::AtomicList),
        field("/spec/tls/*/hosts/*", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/tls/*/secretName", 20, 21, None, MergeStrategy::Scalar),
    ]
});
static FIELDS_7: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 37, None, MergeStrategy::Scalar),
        field("/spec", 20, 37, None, MergeStrategy::Object),
        field("/spec/controller", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/parameters", 20, 37, None, MergeStrategy::Object),
        field("/spec/parameters/apiGroup", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/parameters/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/parameters/name", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/spec/parameters/namespace",
            23,
            37,
            Some(FeatureGateId::IngressClassNamespacedParams),
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/parameters/scope",
            23,
            37,
            Some(FeatureGateId::IngressClassNamespacedParams),
            MergeStrategy::Scalar,
        ),
    ]
});
static FIELDS_8: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 21, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 21, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 21, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 21, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 21, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            21,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 21, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            21,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 21, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 21, None, MergeStrategy::Scalar),
        field("/spec", 20, 21, None, MergeStrategy::Object),
        field("/spec/controller", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/parameters", 20, 21, None, MergeStrategy::Object),
        field("/spec/parameters/apiGroup", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/parameters/kind", 20, 21, None, MergeStrategy::Scalar),
        field("/spec/parameters/name", 20, 21, None, MergeStrategy::Scalar),
        field(
            "/spec/parameters/namespace",
            23,
            21,
            Some(FeatureGateId::IngressClassNamespacedParams),
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/parameters/scope",
            23,
            21,
            Some(FeatureGateId::IngressClassNamespacedParams),
            MergeStrategy::Scalar,
        ),
    ]
});
static FIELDS_9: LazyLock<Vec<FieldCapability>> = LazyLock::new(|| {
    vec![
        field("/metadata", 20, 37, None, MergeStrategy::Object),
        field("/metadata/annotations", 20, 37, None, MergeStrategy::Map),
        field("/metadata/annotations/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/finalizers", 20, 37, None, MergeStrategy::AtomicList),
        field("/metadata/finalizers/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/generateName", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/labels", 20, 37, None, MergeStrategy::Map),
        field("/metadata/labels/*", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/namespace", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/metadata/ownerReferences",
            20,
            37,
            None,
            MergeStrategy::MapList { keys: &["uid"] },
        ),
        field("/metadata/ownerReferences/*", 20, 37, None, MergeStrategy::Object),
        field(
            "/metadata/ownerReferences/*/apiVersion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/blockOwnerDeletion",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/metadata/ownerReferences/*/controller",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/metadata/ownerReferences/*/kind", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/name", 20, 37, None, MergeStrategy::Scalar),
        field("/metadata/ownerReferences/*/uid", 20, 37, None, MergeStrategy::Scalar),
        field("/spec", 20, 37, None, MergeStrategy::Object),
        field("/spec/egress", 20, 37, None, MergeStrategy::AtomicList),
        field("/spec/egress/*", 20, 37, None, MergeStrategy::Object),
        field("/spec/egress/*/ports", 20, 37, None, MergeStrategy::AtomicList),
        field("/spec/egress/*/ports/*", 20, 37, None, MergeStrategy::Object),
        field("/spec/egress/*/ports/*/port", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/egress/*/ports/*/protocol", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/egress/*/to", 20, 37, None, MergeStrategy::AtomicList),
        field("/spec/egress/*/to/*", 20, 37, None, MergeStrategy::Object),
        field("/spec/egress/*/to/*/ipBlock", 20, 37, None, MergeStrategy::Object),
        field("/spec/egress/*/to/*/ipBlock/cidr", 20, 37, None, MergeStrategy::Scalar),
        field(
            "/spec/egress/*/to/*/ipBlock/except",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/egress/*/to/*/ipBlock/except/*",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/egress/*/to/*/namespaceSelector",
            20,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/egress/*/to/*/namespaceSelector/matchExpressions",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/egress/*/to/*/namespaceSelector/matchExpressions/*",
            20,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/egress/*/to/*/namespaceSelector/matchExpressions/*/key",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/egress/*/to/*/namespaceSelector/matchExpressions/*/operator",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/egress/*/to/*/namespaceSelector/matchExpressions/*/values",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/egress/*/to/*/namespaceSelector/matchExpressions/*/values/*",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/egress/*/to/*/namespaceSelector/matchLabels",
            20,
            37,
            None,
            MergeStrategy::Map,
        ),
        field(
            "/spec/egress/*/to/*/namespaceSelector/matchLabels/*",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/egress/*/to/*/podSelector", 20, 37, None, MergeStrategy::Object),
        field(
            "/spec/egress/*/to/*/podSelector/matchExpressions",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/egress/*/to/*/podSelector/matchExpressions/*",
            20,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/egress/*/to/*/podSelector/matchExpressions/*/key",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/egress/*/to/*/podSelector/matchExpressions/*/operator",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/egress/*/to/*/podSelector/matchExpressions/*/values",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/egress/*/to/*/podSelector/matchExpressions/*/values/*",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/egress/*/to/*/podSelector/matchLabels",
            20,
            37,
            None,
            MergeStrategy::Map,
        ),
        field(
            "/spec/egress/*/to/*/podSelector/matchLabels/*",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/ingress", 20, 37, None, MergeStrategy::AtomicList),
        field("/spec/ingress/*", 20, 37, None, MergeStrategy::Object),
        field("/spec/ingress/*/from", 20, 37, None, MergeStrategy::AtomicList),
        field("/spec/ingress/*/from/*", 20, 37, None, MergeStrategy::Object),
        field("/spec/ingress/*/from/*/ipBlock", 20, 37, None, MergeStrategy::Object),
        field(
            "/spec/ingress/*/from/*/ipBlock/cidr",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/ingress/*/from/*/ipBlock/except",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/ingress/*/from/*/ipBlock/except/*",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/ingress/*/from/*/namespaceSelector",
            20,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/ingress/*/from/*/namespaceSelector/matchExpressions",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/ingress/*/from/*/namespaceSelector/matchExpressions/*",
            20,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/ingress/*/from/*/namespaceSelector/matchExpressions/*/key",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/ingress/*/from/*/namespaceSelector/matchExpressions/*/operator",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/ingress/*/from/*/namespaceSelector/matchExpressions/*/values",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/ingress/*/from/*/namespaceSelector/matchExpressions/*/values/*",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/ingress/*/from/*/namespaceSelector/matchLabels",
            20,
            37,
            None,
            MergeStrategy::Map,
        ),
        field(
            "/spec/ingress/*/from/*/namespaceSelector/matchLabels/*",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/ingress/*/from/*/podSelector",
            20,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/ingress/*/from/*/podSelector/matchExpressions",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/ingress/*/from/*/podSelector/matchExpressions/*",
            20,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/ingress/*/from/*/podSelector/matchExpressions/*/key",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/ingress/*/from/*/podSelector/matchExpressions/*/operator",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/ingress/*/from/*/podSelector/matchExpressions/*/values",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/ingress/*/from/*/podSelector/matchExpressions/*/values/*",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/ingress/*/from/*/podSelector/matchLabels",
            20,
            37,
            None,
            MergeStrategy::Map,
        ),
        field(
            "/spec/ingress/*/from/*/podSelector/matchLabels/*",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/ingress/*/ports", 20, 37, None, MergeStrategy::AtomicList),
        field("/spec/ingress/*/ports/*", 20, 37, None, MergeStrategy::Object),
        field("/spec/ingress/*/ports/*/port", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/ingress/*/ports/*/protocol", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/podSelector", 20, 37, None, MergeStrategy::Object),
        field(
            "/spec/podSelector/matchExpressions",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/podSelector/matchExpressions/*",
            20,
            37,
            None,
            MergeStrategy::Object,
        ),
        field(
            "/spec/podSelector/matchExpressions/*/key",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/podSelector/matchExpressions/*/operator",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field(
            "/spec/podSelector/matchExpressions/*/values",
            20,
            37,
            None,
            MergeStrategy::AtomicList,
        ),
        field(
            "/spec/podSelector/matchExpressions/*/values/*",
            20,
            37,
            None,
            MergeStrategy::Scalar,
        ),
        field("/spec/podSelector/matchLabels", 20, 37, None, MergeStrategy::Map),
        field("/spec/podSelector/matchLabels/*", 20, 37, None, MergeStrategy::Scalar),
        field("/spec/policyTypes", 20, 37, None, MergeStrategy::AtomicList),
        field("/spec/policyTypes/*", 20, 37, None, MergeStrategy::Scalar),
    ]
});
pub(super) fn for_api(gvk: GroupVersionKind) -> Result<KindCapability, Finding> {
    let (index, scope, first, last) = match (gvk.kind.as_str(), gvk.api_version().as_str()) {
        ("Service", "v1") => (0, ResourceScope::Namespaced, 20, 37),
        ("Endpoints", "v1") => (1, ResourceScope::Namespaced, 20, 37),
        ("EndpointSlice", "discovery.k8s.io/v1") => (2, ResourceScope::Namespaced, 21, 37),
        ("EndpointSlice", "discovery.k8s.io/v1beta1") => (3, ResourceScope::Namespaced, 20, 24),
        ("Ingress", "extensions/v1beta1") => (4, ResourceScope::Namespaced, 20, 21),
        ("Ingress", "networking.k8s.io/v1") => (5, ResourceScope::Namespaced, 20, 37),
        ("Ingress", "networking.k8s.io/v1beta1") => (6, ResourceScope::Namespaced, 20, 21),
        ("IngressClass", "networking.k8s.io/v1") => (7, ResourceScope::Cluster, 20, 37),
        ("IngressClass", "networking.k8s.io/v1beta1") => (8, ResourceScope::Cluster, 20, 21),
        ("NetworkPolicy", "networking.k8s.io/v1") => (9, ResourceScope::Namespaced, 20, 37),
        _ => return Err(Finding::error(FindingCode::UnavailableApi, Phase::Validation)),
    };
    let fields = match index {
        0 => &FIELDS_0,
        1 => &FIELDS_1,
        2 => &FIELDS_2,
        3 => &FIELDS_3,
        4 => &FIELDS_4,
        5 => &FIELDS_5,
        6 => &FIELDS_6,
        7 => &FIELDS_7,
        8 => &FIELDS_8,
        9 => &FIELDS_9,
        _ => return Err(Finding::error(FindingCode::UnavailableApi, Phase::Validation)),
    };
    Ok(KindCapability {
        gvk,
        scope,
        api_since: version(first),
        api_removed: (last < 37).then(|| version(last + 1)),
        fields,
    })
}

/// Reviewed scalar default spellings, separate from immutable schema enum evidence.
pub(crate) fn source_default_enum(
    gvk: &GroupVersionKind,
    node: &crate::syntax::TreeNode,
    path: &crate::diagnostic::FieldPath,
) -> bool {
    if gvk.group.is_some() || gvk.version != "v1" || node.as_str() != Some("") {
        return false;
    }
    match (gvk.kind.as_str(), path.0.as_slice()) {
        ("Service", [spec, field]) => spec == "spec" && matches!(field.as_str(), "type" | "sessionAffinity"),
        ("Service", [spec, ports, index, protocol]) => {
            spec == "spec" && ports == "ports" && protocol == "protocol" && index.parse::<usize>().is_ok()
        }
        ("Endpoints", [subsets, subset, ports, index, protocol]) => {
            subsets == "subsets"
                && ports == "ports"
                && protocol == "protocol"
                && subset.parse::<usize>().is_ok()
                && index.parse::<usize>().is_ok()
        }
        _ => false,
    }
}
