//! Deterministic private in-memory output and merge-safe live typed deltas.
use crate::{
    capability::{FeatureGateState, FieldAdmission, FieldCapability, MergeStrategy, TargetProfile, declaration},
    diagnostic::{FieldPath, Finding, FindingCode, Phase, ResourceId, Severity, WrapperSubject, has_errors},
    model::{FieldEdit, ResourceSet},
    processing::{NativeOperationBudget, NativeProcessingLimits, ProcessingReport},
    registry::ValidationContext,
    syntax::{TreeNode, TreeValue},
};
use std::{
    collections::{BTreeMap, BTreeSet},
    fmt,
    sync::Arc,
};
/// Explicit output syntax.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OutputFormat {
    /// Deterministic YAML document stream.
    Yaml,
    /// Strict deterministic JSON.
    Json,
}
/// Explicit JSON collection shape.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum JsonShape {
    /// Exactly one native document.
    SingleResource,
    /// A generic Kubernetes List.
    KubernetesList,
}
/// Explicit native validation operation; never inferred from source or output origin.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum NativeValidationIntent {
    /// Operation-dependent rules remain unverified and produce safe findings.
    #[default]
    Unspecified,
    /// Validate the reviewed create-specific rules, without executing a request.
    Create,
}
/// Native source intent independent of source origin.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OutputIntent {
    /// Retain supplied observations under the same target/opaque/protected checks.
    PreserveObservation,
    /// Retain observations unless explicitly edited.
    PreserveDocument,
    /// Remove only recognized server-owned fields with findings.
    AuthoredIntent,
}
/// No synthetic placeholder output exists.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProtectedOutput {
    /// Refuse any protected/private opaque payload.
    Deny,
    /// Explicitly authorize actual native payload bytes.
    Include,
}
/// Opaque preservation is separate from typed/native admission.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OpaqueFieldPolicy {
    /// Fail when field availability cannot be established.
    Block,
    /// Explicitly preserve with unadmitted findings.
    PreserveWithFinding,
}
/// Native wrapper retention is an explicit caller decision.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CollectionOutput {
    /// Keep source List wrappers and metadata/order.
    PreserveWrappers,
    /// Emit native items in a deterministic stream.
    Flatten,
}
/// Explicit private-output, admission, and intent policies.
#[derive(Clone, Debug)]
pub struct GenerationOptions {
    /// Optional operation ceiling; it can only lower retained/default processing limits.
    pub processing: Option<NativeProcessingLimits>,
    /// Default denies private values.
    pub protected_output: ProtectedOutput,
    /// Default blocks opaque availability.
    pub opaque_fields: OpaqueFieldPolicy,
    /// Strict JSON shape.
    pub json_shape: JsonShape,
    /// Explicit output intent.
    pub intent: OutputIntent,
    /// Native operation context, independent of output intent and source origin.
    pub validation_intent: NativeValidationIntent,
    /// Explicit YAML/JSON collection policy.
    pub collections: CollectionOutput,
}
impl Default for GenerationOptions {
    fn default() -> Self {
        Self {
            processing: None,
            protected_output: ProtectedOutput::Deny,
            opaque_fields: OpaqueFieldPolicy::Block,
            json_shape: JsonShape::KubernetesList,
            intent: OutputIntent::PreserveDocument,
            validation_intent: NativeValidationIntent::Unspecified,
            collections: CollectionOutput::PreserveWrappers,
        }
    }
}
/// Explicit private artifact access token.
#[derive(Clone, Copy, Debug)]
pub struct ExplicitArtifactAccess(());
impl ExplicitArtifactAccess {
    /// Deliberately authorize raw generated bytes.
    #[must_use]
    pub const fn explicitly_allow_raw_artifact() -> Self {
        Self(())
    }
}
/// Generated bytes remain private and do not imply compatibility or deployment.
pub struct GeneratedArtifact {
    format: OutputFormat,
    bytes: Arc<[u8]>,
    findings: Vec<Finding>,
}
impl GeneratedArtifact {
    /// Selected syntax.
    #[must_use]
    pub const fn format(&self) -> OutputFormat {
        self.format
    }
    /// Structured outcomes, never source values.
    #[must_use]
    pub fn findings(&self) -> &[Finding] {
        &self.findings
    }
    /// Reveal native bytes only after explicit authorization.
    #[must_use]
    pub fn reveal_bytes(&self, _access: &ExplicitArtifactAccess) -> &[u8] {
        &self.bytes
    }
}
impl fmt::Debug for GeneratedArtifact {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("GeneratedArtifact")
            .field("format", &self.format)
            .field("byte_len", &self.bytes.len())
            .field("findings", &self.findings)
            .finish_non_exhaustive()
    }
}
fn validate_wrapper(list: &crate::model::ListDocument, target: &TargetProfile, findings: &mut ProcessingReport) {
    let processing = findings.processing().clone();
    if findings.failed() || processing.work(1, Phase::Validation).is_err() {
        return;
    }
    let root_lookup_work = list
        .original
        .as_mapping()
        .map_or(Some(0), |entries| entries.len().checked_mul(5));
    let Some(root_lookup_work) = root_lookup_work else {
        processing.fail(Phase::Validation);
        return;
    };
    if processing.work(root_lookup_work, Phase::Validation).is_err() {
        return;
    }
    if let Some(metadata) = list.original.get("metadata") {
        if let Some(entries) = metadata.as_mapping() {
            for (key, node) in entries {
                if findings.failed()
                    || processing.work(1, Phase::Validation).is_err()
                    || processing.work(key.len(), Phase::Validation).is_err()
                {
                    return;
                }
                let valid = match key.as_str() {
                    "resourceVersion" | "selfLink" | "continue" => {
                        matches!(node.value, TreeValue::String(_) | TreeValue::Null)
                    }
                    "remainingItemCount" => {
                        matches!(&node.value, TreeValue::Number(value) if value.parse::<u64>().is_ok())
                            || node.value == TreeValue::Null
                    }
                    _ => true,
                };
                if !valid {
                    findings.push(wrapper_finding(
                        list,
                        FindingCode::NativeFieldInvalid,
                        Phase::Validation,
                        FieldPath(vec!["metadata".into(), key.clone()]),
                        true,
                    ));
                    if findings.failed() {
                        return;
                    }
                }
            }
        } else {
            findings.push(wrapper_finding(
                list,
                FindingCode::NativeFieldInvalid,
                Phase::Validation,
                FieldPath(vec!["metadata".into()]),
                true,
            ));
        }
    }
    if findings.failed() {
        return;
    }
    for name in ["apiVersion", "kind"] {
        let bytes = list.original.get(name).and_then(TreeNode::as_str).map_or(0, str::len);
        if processing.payload(bytes, Phase::Validation).is_err() {
            return;
        }
    }
    let Ok(mut gvk) = crate::model::tree_gvk(&list.original) else {
        return;
    };
    if gvk.group.is_none() && gvk.version == "v1" && gvk.kind == "List" {
        return;
    }
    if let Some(kind) = gvk.kind.strip_suffix("List") {
        if processing.payload(kind.len(), Phase::Validation).is_err() {
            return;
        }
        gvk.kind = kind.to_owned();
    }
    if declaration(&gvk).is_some_and(|decl| !(decl.first..=decl.last).contains(&target.kubernetes.minor()))
        || declaration(&gvk).is_none() && crate::capability::builtin_scope(&gvk).is_some()
    {
        findings.push(wrapper_finding(
            list,
            FindingCode::UnavailableApi,
            Phase::Validation,
            FieldPath::default(),
            true,
        ));
    }
    crate::capability::source_field_findings(
        &list.original,
        &gvk,
        target,
        &processing,
        Phase::Validation,
        &mut WrapperFindingSink { list, findings },
    );
}
/// Validate current resources and every retained List against the explicit target.
#[must_use]
pub fn validate_for_target(resources: &ResourceSet, target: &TargetProfile) -> Vec<Finding> {
    validate_for_target_with_intent(resources, target, NativeValidationIntent::Unspecified)
}
/// Validate the same effective native trees with explicitly supplied operation context.
/// This does not establish API-server conformance or authorize execution.
#[must_use]
pub fn validate_for_target_with_intent(
    resources: &ResourceSet,
    target: &TargetProfile,
    intent: NativeValidationIntent,
) -> Vec<Finding> {
    validate_in(resources, target, intent, resources.operation(None))
}
/// Validate under an explicitly lower operation ceiling without changing native source evidence.
/// # Errors
/// Violations and limits are returned as structured findings, never server-validation claims.
#[must_use]
pub fn validate_for_target_with_limits(
    resources: &ResourceSet,
    target: &TargetProfile,
    intent: NativeValidationIntent,
    limits: &NativeProcessingLimits,
) -> Vec<Finding> {
    validate_in(resources, target, intent, resources.operation(Some(*limits)))
}
pub(crate) fn validate_in(
    resources: &ResourceSet,
    target: &TargetProfile,
    intent: NativeValidationIntent,
    processing: NativeOperationBudget,
) -> Vec<Finding> {
    let construction = resources.encoding(Some(target), processing.clone());
    let construction = crate::registry::EncodeContext {
        budget: construction.budget.for_phase(Phase::Validation),
        ..construction
    };
    let mut findings = ProcessingReport::new(processing, Phase::Validation);
    findings.extend(target.findings());
    resources.identity_findings_into(false, Some(&construction), &mut findings);
    for list in &resources.lists {
        if findings.failed() {
            break;
        }
        validate_wrapper(list, target, &mut findings);
    }
    for document in &resources.documents {
        if findings.failed() {
            break;
        }
        let context = construction.for_source(*document.evidence.limits());
        let tree = match document.current_tree_in(Some(target), Some(&context)) {
            Ok(tree) => tree,
            Err(error) => {
                if error.code == FindingCode::MergeConflict {
                    let mut native =
                        Finding::error(FindingCode::NativeFieldInvalid, Phase::Validation).for_resource(document.id);
                    native.path.clone_from(&error.path);
                    native.source = error.source;
                    findings.push(native);
                }
                findings.push(error.for_resource(document.id));
                continue;
            }
        };
        let identity = match crate::model::identity_in(
            &tree,
            document.original_identity.scope,
            findings.processing(),
            Phase::Validation,
        ) {
            Ok(identity) => identity,
            Err(error) => {
                findings.push(error.for_resource(document.id));
                continue;
            }
        };
        validate_api(&identity, document.id, target, &mut findings);
        validate_source_fields(&tree, &identity.gvk, document.id, target, &mut findings);
        if let Some(capability) = &document.capability {
            if target.kubernetes < capability.api_since
                || capability
                    .api_removed
                    .is_some_and(|removed| target.kubernetes >= removed)
            {
                findings.push(Finding::error(FindingCode::UnavailableApi, Phase::Validation).for_resource(document.id));
            }
            for field in capability.fields {
                if findings.failed() {
                    break;
                }
                if field_nodes(&tree, field.path).is_empty() {
                    continue;
                }
                let path = FieldPath::parse(field.path).ok();
                let code = if target.kubernetes < field.since
                    || field.removed.is_some_and(|removed| target.kubernetes >= removed)
                {
                    Some(FindingCode::UnavailableField)
                } else if field.feature_gate.is_some_and(|gate| {
                    target.feature_gates.resolve(gate, target.kubernetes) != Ok(FeatureGateState::Enabled)
                }) {
                    Some(FindingCode::FeatureGateRequired)
                } else if field.admission != FieldAdmission::Typed {
                    Some(FindingCode::UnadmittedField)
                } else {
                    None
                };
                if let Some(code) = code {
                    let mut f = Finding::error(code, Phase::Validation).for_resource(document.id);
                    f.path = path;
                    findings.push(f);
                }
            }
        } else {
            findings.push(
                Finding::warning(
                    if declaration(&identity.gvk).is_some() {
                        FindingCode::UnadmittedKind
                    } else {
                        FindingCode::UnknownKind
                    },
                    Phase::Validation,
                )
                .for_resource(document.id),
            );
        }
        validate_native(document, &tree, &identity, target, intent, &context, &mut findings);
    }
    findings.into_vec()
}
fn validate_source_fields(
    tree: &TreeNode,
    gvk: &crate::model::GroupVersionKind,
    resource: ResourceId,
    target: &TargetProfile,
    findings: &mut ProcessingReport,
) {
    let processing = findings.processing().clone();
    crate::capability::source_field_findings(
        tree,
        gvk,
        target,
        &processing,
        Phase::Validation,
        &mut crate::registry::ResourceFindingSink {
            sink: findings,
            resource,
        },
    );
}

fn validate_api(
    identity: &crate::model::ResourceIdentity,
    id: ResourceId,
    target: &TargetProfile,
    findings: &mut ProcessingReport,
) {
    if let Some(decl) = declaration(&identity.gvk) {
        if !(decl.first..=decl.last).contains(&target.kubernetes.minor()) {
            findings.push(Finding::error(FindingCode::UnavailableApi, Phase::Validation).for_resource(id));
        }
    } else if crate::capability::builtin_scope(&identity.gvk).is_some() {
        findings.push(Finding::error(FindingCode::UnavailableApi, Phase::Validation).for_resource(id));
    } else if identity.scope == crate::model::ResourceScope::Unknown {
        findings.push(Finding::warning(FindingCode::ScopeUnknown, Phase::Validation).for_resource(id));
    }
}
fn validate_native(
    document: &crate::model::ResourceDocument,
    tree: &TreeNode,
    identity: &crate::model::ResourceIdentity,
    target: &TargetProfile,
    intent: NativeValidationIntent,
    context: &crate::registry::EncodeContext<'_>,
    findings: &mut ProcessingReport,
) {
    if findings.failed() {
        return;
    }
    if let Some(decode) = document.decode {
        match decode(
            tree,
            &document.evidence,
            &crate::registry::DecodeContext {
                gvk: &identity.gvk,
                scope: identity.scope,
                fields: context.fields(Phase::Validation),
            },
        ) {
            Ok(resource) => {
                let mut sink = crate::registry::ResourceFindingSink {
                    sink: findings,
                    resource: document.id,
                };
                resource.validate(
                    &ValidationContext {
                        intent,
                        target,
                        fields: context.fields(Phase::Validation),
                    },
                    &mut sink,
                );
            }
            Err(errors) => findings.extend(errors.into_iter().map(|finding| finding.for_resource(document.id))),
        }
    }
}
fn bounded_json(node: &TreeNode, out: &mut String, processing: &NativeOperationBudget) -> Result<(), Finding> {
    fn bound(node: &TreeNode, processing: &NativeOperationBudget) -> Result<usize, Finding> {
        processing.work(1, Phase::Generation)?;
        let fail = || processing.fail(Phase::Generation);
        match &node.value {
            TreeValue::String(value) => value
                .len()
                .checked_mul(6)
                .and_then(|bytes| bytes.checked_add(2))
                .ok_or_else(fail),
            TreeValue::Number(value) => Ok(value.len()),
            TreeValue::Mapping(entries) => entries.iter().try_fold(2usize, |total, (key, node)| {
                let key = key
                    .len()
                    .checked_mul(6)
                    .and_then(|bytes| bytes.checked_add(4))
                    .ok_or_else(fail)?;
                total
                    .checked_add(key)
                    .and_then(|total| total.checked_add(bound(node, processing).ok()?))
                    .ok_or_else(fail)
            }),
            TreeValue::Sequence(items) => items.iter().try_fold(2usize, |total, node| {
                total
                    .checked_add(1)
                    .and_then(|total| total.checked_add(bound(node, processing).ok()?))
                    .ok_or_else(fail)
            }),
            _ => Ok(5),
        }
    }
    let upper = bound(node, processing)?;
    let payload = upper.checked_mul(2).ok_or_else(|| processing.fail(Phase::Generation))?;
    processing.payload(payload, Phase::Generation)?;
    processing.work(upper, Phase::Generation)?;
    out.reserve_exact(upper);
    json(node, out)
}
pub(crate) fn field_nodes<'a>(tree: &'a TreeNode, pointer: &str) -> Vec<&'a TreeNode> {
    let Ok(path) = FieldPath::parse(pointer) else {
        return Vec::new();
    };
    let mut nodes = vec![tree];
    for segment in &path.0 {
        let mut next = Vec::new();
        for node in nodes {
            if segment == "*" {
                match &node.value {
                    TreeValue::Sequence(items) => next.extend(items),
                    TreeValue::Mapping(entries) => next.extend(entries.iter().map(|(_, v)| v)),
                    _ => {}
                }
            } else if let Some(value) = node.get(segment) {
                next.push(value);
            }
        }
        nodes = next;
    }
    nodes
}
/// Generate current native values without files, processes, clusters, or implicit migration.
/// # Errors
/// Blocks invalid targets/identities, unavailable APIs/fields, opaque/private output, and lossy edits.
pub fn generate(
    resources: &ResourceSet,
    target: &TargetProfile,
    format: OutputFormat,
    options: &GenerationOptions,
) -> Result<GeneratedArtifact, Vec<Finding>> {
    let processing = resources.operation(options.processing);
    let construction = resources.encoding(Some(target), processing.clone());
    let mut findings = ProcessingReport::from_report(
        validate_in(resources, target, options.validation_intent, processing.clone()),
        processing.clone(),
        Phase::Generation,
    );
    let mut trees = BTreeMap::new();
    for doc in &resources.documents {
        if findings.failed() {
            break;
        }
        let context = construction.for_source(*doc.evidence.limits());
        let projection = match doc.project_in(Some(target), Some(&context)) {
            Ok(projection) => projection,
            Err(errors) => {
                findings.extend(errors);
                continue;
            }
        };
        findings.extend(projection.findings);
        let mut tree = projection.tree;
        if let Err(error) = apply_observation_output(
            doc,
            &mut tree,
            projection.observations,
            options,
            &mut findings,
            &processing,
        ) {
            findings.push(error);
            break;
        }
        preserve_access_mode_findings(doc, &tree, &projection.occurrences, options, &processing, &mut findings);
        if options.opaque_fields == OpaqueFieldPolicy::Block
            && (doc.resource.is_none() || has_unknown_fields(&tree, doc.capability.as_ref().map_or(&[], |c| c.fields)))
        {
            findings.push(Finding::error(FindingCode::OpaqueOutputDenied, Phase::Generation).for_resource(doc.id));
        }
        let mut protected_paths = Vec::new();
        if let Some(resource) = &projection.resource {
            resource.collect_protected_paths(&context, &mut protected_paths);
        }
        let codec_protected = protected_paths
            .iter()
            .any(|path| tree.get_path(path).is_some_and(|node| node.value != TreeValue::Null));
        if options.protected_output == ProtectedOutput::Deny
            && (codec_protected
                || protected(&tree)
                || doc.original_identity.scope.namespaced().is_none()
                || matches!(
                    doc.original_identity.scope,
                    crate::model::ResourceScope::CrdResolved { .. }
                ))
        {
            findings.push(Finding::error(FindingCode::ProtectedOutputDenied, Phase::Generation).for_resource(doc.id));
        }
        if contains_tags(&tree) {
            findings.push(Finding::error(FindingCode::UnsupportedScalar, Phase::Generation).for_resource(doc.id));
        }
        trees.insert(doc.id, tree);
    }
    let wrappers = prepare_wrappers(resources, options, &processing, &mut findings);
    if findings.failed() || has_errors(&findings) {
        return Err(findings.into_vec());
    }
    let roots = match output_roots(resources, options.collections, &mut trees, &wrappers, &processing) {
        Ok(roots) => roots,
        Err(finding) => {
            findings.push(finding);
            return Err(findings.into_vec());
        }
    };
    let bytes = match serialize_roots(roots, format, options.json_shape, &processing) {
        Ok(bytes) => bytes,
        Err(finding) => {
            findings.push(finding);
            return Err(findings.into_vec());
        }
    };
    if let Err(finding) = processing.payload(bytes.len(), Phase::Generation) {
        findings.push(finding);
        return Err(findings.into_vec());
    }
    Ok(GeneratedArtifact {
        format,
        bytes: Arc::from(bytes.into_bytes()),
        findings: findings.into_vec(),
    })
}
/// Preservation changes the outcome severity, never finite admission or retained source evidence.
fn preserve_access_mode_findings(
    document: &crate::model::ResourceDocument,
    tree: &TreeNode,
    occurrences: &crate::syntax::NativeOccurrences,
    options: &GenerationOptions,
    processing: &NativeOperationBudget,
    findings: &mut ProcessingReport,
) {
    if options.opaque_fields != OpaqueFieldPolicy::PreserveWithFinding
        || options.protected_output != ProtectedOutput::Include
    {
        return;
    }
    for finding in findings.entries_mut() {
        if processing.work(1, Phase::Generation).is_err() {
            return;
        }
        if finding.code != FindingCode::UnadmittedField || finding.resource != Some(document.id) {
            continue;
        }
        let Some(path) = &finding.path else {
            continue;
        };
        let Some((_, parents)) = path.0.split_last() else {
            continue;
        };
        if parents.last().is_none_or(|segment| segment != "accessModes") {
            continue;
        }
        if processing
            .payload_array::<String>(parents.len(), Phase::Generation)
            .is_err()
            || parents
                .iter()
                .any(|segment| processing.payload(segment.len(), Phase::Generation).is_err())
        {
            return;
        }
        let collection = FieldPath(parents.to_vec());
        let Some(value) = tree.get_path(path).and_then(TreeNode::as_str) else {
            continue;
        };
        if crate::value::EstablishedVolumeAccessMode::selected(value).is_some() {
            continue;
        }
        match supplied_access_mode_occurrence(document, tree, occurrences, &collection, processing) {
            Ok(true) => finding.severity = Severity::Warning,
            Ok(false) => {}
            Err(_) => return,
        }
    }
}
fn supplied_access_mode_occurrence(
    document: &crate::model::ResourceDocument,
    tree: &TreeNode,
    occurrences: &crate::syntax::NativeOccurrences,
    path: &FieldPath,
    processing: &NativeOperationBudget,
) -> Result<bool, Finding> {
    processing.work(1, Phase::Generation)?;
    if !matches!(document.evidence.origin, crate::source::EvidenceOrigin::Supplied(_)) {
        return Ok(false);
    }
    for edit in &document.edits {
        processing.work(1, Phase::Generation)?;
        let edited = match edit {
            FieldEdit::Set { path, .. } | FieldEdit::Remove { path } => path,
        };
        if path.0.starts_with(&edited.0) || edited.0.starts_with(&path.0) {
            return Ok(false);
        }
    }
    let (Some(before), Some(after)) = (document.original.get_path(path), tree.get_path(path)) else {
        return Ok(false);
    };
    if before.as_sequence().is_none() || after.as_sequence().is_none() {
        return Ok(false);
    }
    let context = BudgetedMergeContext {
        native: MergeContext {
            gvk: Some(&document.original_identity.gvk),
            target: None,
        },
        processing,
        phase: Phase::Generation,
    };
    if !merge_semantic_eq(before, after, context)? {
        return Ok(false);
    }
    // Mutable holders contribute only candidates. Immutable per-document/path
    // anchors plus the actual original/effective complete sequence authorize them.
    let mut native_bound = false;
    for original_path in document.original_occurrences.keys() {
        processing.work(1, Phase::Generation)?;
        for segment in original_path.0.iter().chain(&path.0) {
            processing.work(segment.len().saturating_add(1), Phase::Generation)?;
        }
        if original_path == path {
            native_bound = true;
            break;
        }
    }
    if native_bound {
        if !sealed_occurrence_matches(&document.original_occurrences, occurrences, path, processing)? {
            return Ok(false);
        }
        for ancestor in document.original_occurrences.keys() {
            processing.work(1, Phase::Generation)?;
            for segment in ancestor.0.iter().chain(&path.0) {
                processing.work(segment.len().saturating_add(1), Phase::Generation)?;
            }
            if ancestor != path
                && path.0.starts_with(&ancestor.0)
                && !sealed_occurrence_matches(&document.original_occurrences, occurrences, ancestor, processing)?
            {
                return Ok(false);
            }
        }
    }
    supplied_access_mode_path_occurrence(&document.original, tree, path, native_bound, context)
}

fn supplied_access_mode_path_occurrence(
    original: &TreeNode,
    tree: &TreeNode,
    path: &FieldPath,
    native_bound: bool,
    context: BudgetedMergeContext<'_>,
) -> Result<bool, Finding> {
    // Bind nested occurrences from immutable source/destination trees. No mutable
    // native holder name, cached origin, or blanket ancestor-value equality is authority.
    let processing = context.processing;
    let mut before = original;
    let mut after = tree;
    for segment in &path.0 {
        processing.work(1, Phase::Generation)?;
        if let Some(original_items) = before.as_sequence() {
            let Some(effective_items) = after.as_sequence() else {
                return Ok(false);
            };
            processing.work(segment.len(), Phase::Generation)?;
            let Ok(index) = segment.parse::<usize>() else {
                return Ok(false);
            };
            let (Some(original), Some(effective)) = (original_items.get(index), effective_items.get(index)) else {
                return Ok(false);
            };
            let Some(position) = original.start else {
                return Ok(false);
            };
            if !native_bound && effective.start != Some(position) {
                return Ok(false);
            }
            for items in [Some(original_items), (!native_bound).then_some(effective_items)]
                .into_iter()
                .flatten()
            {
                let mut matches = 0;
                for item in items {
                    processing.work(1, Phase::Generation)?;
                    if item.start == Some(position) {
                        matches += 1;
                    }
                }
                if matches != 1 {
                    return Ok(false);
                }
            }
            before = original;
            after = effective;
        } else {
            let (Some(original), Some(effective)) = (context.get(before, segment)?, context.get(after, segment)?)
            else {
                return Ok(false);
            };
            before = original;
            after = effective;
        }
    }
    Ok(true)
}

fn sealed_occurrence_matches(
    originals: &crate::syntax::NativeOccurrences,
    candidates: &crate::syntax::NativeOccurrences,
    path: &FieldPath,
    processing: &NativeOperationBudget,
) -> Result<bool, Finding> {
    for table in [originals, candidates] {
        for key in table.keys() {
            processing.work(1, Phase::Generation)?;
            for segment in key.0.iter().chain(&path.0) {
                processing.work(segment.len().saturating_add(1), Phase::Generation)?;
            }
        }
    }
    let (Some(original), Some(candidate)) = (originals.get(path), candidates.get(path)) else {
        return Ok(false);
    };
    if !original.same(candidate) {
        return Ok(false);
    }
    for table in [originals, candidates] {
        let mut matches = 0;
        for token in table.values() {
            processing.work(1, Phase::Generation)?;
            if original.same(token) {
                matches += 1;
            }
        }
        if matches != 1 {
            return Ok(false);
        }
    }
    Ok(true)
}

fn output_roots(
    resources: &ResourceSet,
    collections: CollectionOutput,
    trees: &mut BTreeMap<ResourceId, TreeNode>,
    wrappers: &BTreeMap<crate::model::ListId, TreeNode>,
    processing: &NativeOperationBudget,
) -> Result<Vec<TreeNode>, Finding> {
    processing.payload_array::<&crate::model::ResourceDocument>(resources.documents.len(), Phase::Generation)?;
    for tree in trees.values() {
        crate::model::charge_identity(tree, processing, Phase::Generation)?;
    }
    let mut ordered: Vec<_> = resources.documents.iter().collect();
    ordered.sort_by_cached_key(|doc| {
        trees
            .get(&doc.id)
            .and_then(|tree| crate::model::identity(tree, doc.original_identity.scope).ok())
            .map(|identity| (identity.gvk, identity.scope, identity.namespace, identity.name, doc.id))
    });
    let root_count = resources
        .documents
        .len()
        .checked_add(resources.lists.len())
        .ok_or_else(|| processing.fail(Phase::Generation))?;
    processing.payload_array::<TreeNode>(root_count, Phase::Generation)?;
    let mut roots = Vec::new();
    if collections == CollectionOutput::PreserveWrappers {
        for list in resources.lists.iter().filter(|list| list.collection.is_none()) {
            roots.push(rewrap(resources, list.id, trees, wrappers, processing)?);
        }
        roots.extend(
            ordered
                .iter()
                .filter(|doc| doc.collection.is_none())
                .filter_map(|doc| trees.remove(&doc.id)),
        );
    } else {
        roots.extend(ordered.iter().filter_map(|doc| trees.remove(&doc.id)));
    }
    Ok(roots)
}

fn serialize_roots(
    mut roots: Vec<TreeNode>,
    format: OutputFormat,
    shape: JsonShape,
    processing: &NativeOperationBudget,
) -> Result<String, Finding> {
    let mut bytes = String::new();
    match format {
        OutputFormat::Json => {
            let root = match shape {
                JsonShape::SingleResource => {
                    if roots.len() != 1 {
                        return Err(Finding::error(FindingCode::MalformedDocument, Phase::Generation));
                    }
                    roots.remove(0)
                }
                JsonShape::KubernetesList => list_tree(roots),
            };
            bounded_json(&root, &mut bytes, processing)?;
            append_output(&mut bytes, "\n", processing)?;
        }
        OutputFormat::Yaml => {
            for root in roots {
                append_output(&mut bytes, "---\n", processing)?;
                bounded_json(&root, &mut bytes, processing)?;
                append_output(&mut bytes, "\n", processing)?;
            }
        }
    }
    Ok(bytes)
}
fn append_output(out: &mut String, text: &str, processing: &NativeOperationBudget) -> Result<(), Finding> {
    processing.payload(text.len(), Phase::Generation)?;
    processing.work(text.len(), Phase::Generation)?;
    out.reserve_exact(text.len());
    out.push_str(text);
    Ok(())
}
fn prepare_wrappers(
    resources: &ResourceSet,
    options: &GenerationOptions,
    processing: &NativeOperationBudget,
    findings: &mut ProcessingReport,
) -> BTreeMap<crate::model::ListId, TreeNode> {
    let mut wrappers = BTreeMap::new();
    for list in &resources.lists {
        if findings.failed() {
            break;
        }
        if let Err(finding) = processing.tree_copy(&list.original, Phase::Generation) {
            findings.push(finding);
            break;
        }
        let mut tree = list.original.clone();
        let unknown = wrapper_unknown_paths(&tree, list, processing, findings);
        if findings.failed() {
            break;
        }
        if options.opaque_fields == OpaqueFieldPolicy::Block {
            if let Some(path) = &unknown {
                findings.push(wrapper_finding(
                    list,
                    FindingCode::OpaqueOutputDenied,
                    Phase::Generation,
                    path.clone(),
                    true,
                ));
            }
        }
        if options.protected_output == ProtectedOutput::Deny
            && (unknown.is_some()
                || tree
                    .get("metadata")
                    .and_then(|metadata| metadata.get("continue"))
                    .is_some_and(|node| node.value != TreeValue::Null))
        {
            findings.push(wrapper_finding(
                list,
                FindingCode::ProtectedOutputDenied,
                Phase::Generation,
                FieldPath::default(),
                true,
            ));
        }
        if contains_tags(&tree) {
            findings.push(wrapper_finding(
                list,
                FindingCode::UnsupportedScalar,
                Phase::Generation,
                FieldPath::default(),
                true,
            ));
        }
        if options.intent == OutputIntent::AuthoredIntent {
            let begin = findings.len();
            strip_wrapper_observed(&mut tree, findings);
            for finding in &mut findings.entries_mut()[begin..] {
                finding.wrapper = Some(WrapperSubject {
                    source: list.source,
                    list: list.id,
                });
                finding.source = finding
                    .path
                    .as_ref()
                    .and_then(|path| list.original.get_path(path))
                    .and_then(|node| node.start);
            }
        }
        if options.collections == CollectionOutput::Flatten {
            if let Some(entries) = tree.as_mapping() {
                for (key, _) in entries {
                    if !matches!(key.as_str(), "apiVersion" | "kind" | "items") {
                        findings.push(wrapper_finding(
                            list,
                            FindingCode::CollectionFieldRemoved,
                            Phase::Generation,
                            FieldPath(vec![key.clone()]),
                            false,
                        ));
                    }
                }
            }
        }
        wrappers.insert(list.id, tree);
    }
    wrappers
}
fn list_tree(items: Vec<TreeNode>) -> TreeNode {
    TreeNode::mapping(vec![
        ("apiVersion".into(), TreeNode::string("v1")),
        ("kind".into(), TreeNode::string("List")),
        ("items".into(), TreeNode::new(TreeValue::Sequence(items))),
    ])
}
fn rewrap(
    resources: &ResourceSet,
    id: crate::model::ListId,
    trees: &BTreeMap<ResourceId, TreeNode>,
    wrappers: &BTreeMap<crate::model::ListId, TreeNode>,
    processing: &NativeOperationBudget,
) -> Result<TreeNode, Finding> {
    processing.work(resources.lists.len(), Phase::Generation)?;
    let list = resources.lists.iter().find(|list| list.id == id).ok_or_else(conflict)?;
    let result = (|| {
        let original = wrappers.get(&id).ok_or_else(conflict)?;
        processing.tree_copy(original, Phase::Generation)?;
        let mut wrapper = original.clone();
        let Some(items) = wrapper.get("items").and_then(TreeNode::as_sequence) else {
            return Err(conflict());
        };
        let mut current = Vec::new();
        for index in 0..items.len() {
            processing.work(
                resources
                    .lists
                    .len()
                    .checked_add(resources.documents.len())
                    .and_then(|n| n.checked_add(1))
                    .ok_or_else(|| processing.fail(Phase::Generation))?,
                Phase::Generation,
            )?;
            if let Some(nested) = resources.lists.iter().find(|l| {
                l.collection
                    .as_ref()
                    .is_some_and(|path| path.items.last() == Some(&(id, index)))
            }) {
                current.push(rewrap(resources, nested.id, trees, wrappers, processing)?);
            } else if let Some(doc) = resources.documents.iter().find(|d| {
                d.collection
                    .as_ref()
                    .is_some_and(|path| path.items.last() == Some(&(id, index)))
            }) {
                let tree = trees.get(&doc.id).ok_or_else(conflict)?;
                processing.tree_copy(tree, Phase::Generation)?;
                current.push(tree.clone());
            } else {
                return Err(conflict());
            }
        }
        set_child(&mut wrapper, "items", Some(TreeNode::new(TreeValue::Sequence(current))))?;
        Ok(wrapper)
    })();
    result.map_err(|mut finding: Finding| {
        if finding.code == FindingCode::LimitExceeded {
            return finding;
        }
        if finding.wrapper.is_none() {
            finding = finding.for_wrapper(WrapperSubject {
                source: list.source,
                list: id,
            });
        }
        if finding.source.is_none() {
            finding.source = list.original.start;
        }
        finding
    })
}
fn strip_wrapper_observed(tree: &mut TreeNode, findings: &mut ProcessingReport) {
    strip_observation_paths(tree, None, &crate::source::list_observation_paths(), findings);
}
/// Enumerate warnings lazily; retain only the first path needed by output policies.
fn wrapper_unknown_paths(
    tree: &TreeNode,
    list: &crate::model::ListDocument,
    processing: &NativeOperationBudget,
    findings: &mut ProcessingReport,
) -> Option<FieldPath> {
    let mut first = None;
    let mut warn = |path: FieldPath, node: &TreeNode| {
        if first.is_none() {
            first = Some(path.clone());
        }
        let mut finding = Finding::warning(FindingCode::UnadmittedField, Phase::Validation).at_path(path);
        finding.source = node.start.or(list.original.start);
        finding.wrapper = Some(WrapperSubject {
            source: list.source,
            list: list.id,
        });
        findings.push(finding);
        !findings.failed()
    };
    if let Some(entries) = tree.as_mapping() {
        for (key, value) in entries {
            if processing.work(1, Phase::Generation).is_err() {
                break;
            }
            if key == "metadata" {
                if let Some(metadata) = value.as_mapping() {
                    for (name, node) in metadata {
                        if processing.work(1, Phase::Generation).is_err() {
                            return first;
                        }
                        if !matches!(
                            name.as_str(),
                            "resourceVersion" | "selfLink" | "continue" | "remainingItemCount"
                        ) && !warn(FieldPath(vec![key.clone(), name.clone()]), node)
                        {
                            return first;
                        }
                    }
                } else if !warn(FieldPath(vec![key.clone()]), value) {
                    break;
                }
            } else if !matches!(key.as_str(), "apiVersion" | "kind" | "items")
                && !warn(FieldPath(vec![key.clone()]), value)
            {
                break;
            }
        }
    }
    first
}
struct WrapperFindingSink<'a> {
    list: &'a crate::model::ListDocument,
    findings: &'a mut ProcessingReport,
}
impl crate::registry::FindingSink for WrapperFindingSink<'_> {
    fn push(&mut self, mut finding: Finding) {
        // Emergency findings remain pathless and value-free. Attribution is attached
        // before the report sink preflights ordinary finding retention.
        if finding.code != FindingCode::LimitExceeded {
            finding.wrapper = Some(WrapperSubject {
                source: self.list.source,
                list: self.list.id,
            });
            if finding.source.is_none() {
                finding.source = finding
                    .path
                    .as_ref()
                    .and_then(|path| self.list.original.get_path(path))
                    .and_then(|node| node.start)
                    .or(self.list.original.start);
            }
        }
        self.findings.push(finding);
    }
    fn exhausted(&self) -> bool {
        self.findings.failed()
    }
}

fn wrapper_finding(
    list: &crate::model::ListDocument,
    code: FindingCode,
    phase: Phase,
    path: FieldPath,
    blocking: bool,
) -> Finding {
    let mut finding = if blocking {
        Finding::error(code, phase)
    } else {
        Finding::warning(code, phase)
    };
    finding.source = list
        .original
        .get_path(&path)
        .and_then(|node| node.start)
        .or(list.original.start);
    finding.path = Some(path);
    finding.for_wrapper(WrapperSubject {
        source: list.source,
        list: list.id,
    })
}
fn protected(tree: &TreeNode) -> bool {
    tree.get("kind").and_then(TreeNode::as_str) == Some("Secret")
        && ["data", "stringData"]
            .iter()
            .any(|key| tree.get(key).is_some_and(|n| n.value != TreeValue::Null))
}
fn contains_tags(tree: &TreeNode) -> bool {
    match &tree.value {
        TreeValue::Tagged(..) => true,
        TreeValue::Mapping(entries) => entries.iter().any(|(_, n)| contains_tags(n)),
        TreeValue::Sequence(items) => items.iter().any(contains_tags),
        _ => false,
    }
}
fn strip_observation_paths(
    tree: &mut TreeNode,
    id: Option<ResourceId>,
    observations: &[crate::source::ObservationPath],
    findings: &mut ProcessingReport,
) {
    let processing = findings.processing().clone();
    let result = (|| -> Result<(), Finding> {
        processing.work(observations.len(), Phase::Generation)?;
        processing.payload_array::<FieldPath>(observations.len(), Phase::Generation)?;
        let mut paths = Vec::new();
        let mut path_bytes = 0_usize;
        for observation in observations {
            if matches!(
                observation.role,
                crate::source::ObservationRole::ServerOwned | crate::source::ObservationRole::SubresourceOnly
            ) {
                processing.payload_array::<String>(observation.path.0.len(), Phase::Generation)?;
                processing.payload_sizes(observation.path.0.iter().map(String::len), Phase::Generation)?;
                path_bytes = path_bytes
                    .saturating_add(observation.path.0.iter().map(String::len).sum::<usize>())
                    .saturating_add(observation.path.0.len());
                paths.push(observation.path.clone());
            }
        }
        // Comparison sorting is bounded by n^2, including complete string comparisons.
        processing.work(
            path_bytes.saturating_mul(paths.len().saturating_add(1)),
            Phase::Generation,
        )?;
        paths.sort_by(|left, right| left.0.len().cmp(&right.0.len()).then(left.cmp(right)));
        processing.payload_array::<FieldPath>(paths.len(), Phase::Generation)?;
        let mut removed: Vec<FieldPath> = Vec::new();
        for path in paths {
            processing.work(1, Phase::Generation)?;
            let mut covered = false;
            for parent in &removed {
                processing.work(
                    path.0
                        .iter()
                        .map(String::len)
                        .sum::<usize>()
                        .saturating_add(parent.0.iter().map(String::len).sum::<usize>())
                        .saturating_add(1),
                    Phase::Generation,
                )?;
                if path.0.starts_with(&parent.0) {
                    covered = true;
                    break;
                }
            }
            if covered || observation_node(tree, &path, &processing)?.is_none() {
                continue;
            }
            // Both the temporary edit and resulting report retain exact paths.
            for _ in 0..2 {
                processing.payload_array::<String>(path.0.len(), Phase::Generation)?;
                processing.payload_sizes(path.0.iter().map(String::len), Phase::Generation)?;
            }
            apply_edit_in(
                tree,
                &FieldEdit::Remove { path: path.clone() },
                &processing,
                Phase::Generation,
            )?;
            for finding in findings.entries_mut() {
                processing.work(1, Phase::Generation)?;
                if finding.resource == id && finding.code == FindingCode::UnadmittedField {
                    if let Some(found) = &finding.path {
                        processing.work(
                            found
                                .0
                                .iter()
                                .map(String::len)
                                .sum::<usize>()
                                .saturating_add(path.0.iter().map(String::len).sum::<usize>())
                                .saturating_add(found.0.len())
                                .saturating_mul(2),
                            Phase::Generation,
                        )?;
                        if found.0.starts_with(&path.0)
                            || found.0.len() == path.0.len()
                                && found
                                    .0
                                    .iter()
                                    .zip(&path.0)
                                    .all(|(part, actual)| part == "*" || part == actual)
                        {
                            finding.severity = Severity::Warning;
                        }
                    }
                }
            }
            let mut finding =
                Finding::warning(FindingCode::ObservedFieldRemoved, Phase::Generation).at_path(path.clone());
            finding.resource = id;
            finding.severity = Severity::Information;
            findings.push(finding);
            processing.work(0, Phase::Generation)?;
            removed.push(path);
        }
        Ok(())
    })();
    if let Err(error) = result {
        findings.push(error);
    }
}

fn has_unknown_fields(tree: &TreeNode, fields: &[FieldCapability]) -> bool {
    fn visit(node: &TreeNode, path: &FieldPath, fields: &[FieldCapability]) -> bool {
        if path.0.len() == 1 && matches!(path.0[0].as_str(), "apiVersion" | "kind") {
            return false;
        }
        let admitted = fields.iter().any(|field| {
            FieldPath::parse(field.path).is_ok_and(|p| {
                p.0.len() == path.0.len()
                    && p.0.iter().zip(&path.0).all(|(a, b)| a == "*" || a == b)
                    && field.admission == FieldAdmission::Typed
            })
        });
        match &node.value {
            TreeValue::Mapping(entries) => {
                (entries.is_empty() && !path.0.is_empty() && !admitted)
                    || entries.iter().any(|(key, n)| visit(n, &path.child(key), fields))
            }
            TreeValue::Sequence(items) => {
                (items.is_empty() && !admitted)
                    || items
                        .iter()
                        .enumerate()
                        .any(|(index, n)| visit(n, &path.child(index.to_string()), fields))
            }
            _ => !admitted,
        }
    }
    visit(tree, &FieldPath::default(), fields)
}
fn conflict() -> Finding {
    Finding::error(FindingCode::MergeConflict, Phase::Generation)
}
fn strategy(path: &FieldPath, fields: &[FieldCapability]) -> MergeStrategy {
    fields
        .iter()
        .find(|f| {
            FieldPath::parse(f.path)
                .is_ok_and(|p| p.0.len() == path.0.len() && p.0.iter().zip(&path.0).all(|(a, b)| a == "*" || a == b))
        })
        .map_or(MergeStrategy::AtomicList, |f| f.merge)
}
fn unknown_descendants(raw: &TreeNode, known: &TreeNode, context: BudgetedMergeContext<'_>) -> Result<bool, Finding> {
    context.tick()?;
    match (&raw.value, &known.value) {
        (TreeValue::Mapping(raw), TreeValue::Mapping(_)) => {
            for (key, value) in raw {
                context.tick()?;
                let Some(known) = context.get(known, key)? else {
                    return Ok(true);
                };
                if unknown_descendants(value, known, context)? {
                    return Ok(true);
                }
            }
        }
        (TreeValue::Sequence(raw), TreeValue::Sequence(known)) => {
            if raw.len() != known.len() {
                return Ok(true);
            }
            for (raw, known) in raw.iter().zip(known) {
                if unknown_descendants(raw, known, context)? {
                    return Ok(true);
                }
            }
        }
        _ => {}
    }
    Ok(false)
}
/// Compare borrowed trees without constructing the uncharged mapping index used by `semantic_eq`.
pub(crate) fn merge_semantic_eq(
    left: &TreeNode,
    right: &TreeNode,
    context: BudgetedMergeContext<'_>,
) -> Result<bool, Finding> {
    context.tick()?;
    match (&left.value, &right.value) {
        (TreeValue::Mapping(left), TreeValue::Mapping(right)) => {
            if left.len() != right.len() {
                return Ok(false);
            }
            for (key, value) in left {
                let mut found = None;
                // semantic_eq's BTreeMap keeps the last duplicate mapping key.
                for (name, other) in right.iter().rev() {
                    context
                        .processing
                        .work(name.len().saturating_add(key.len()), context.phase)?;
                    context.tick()?;
                    if name == key {
                        found = Some(other);
                        break;
                    }
                }
                let Some(other) = found else {
                    return Ok(false);
                };
                if !merge_semantic_eq(value, other, context)? {
                    return Ok(false);
                }
            }
            Ok(true)
        }
        (TreeValue::Sequence(left), TreeValue::Sequence(right)) => {
            if left.len() != right.len() {
                return Ok(false);
            }
            for (left, right) in left.iter().zip(right) {
                if !merge_semantic_eq(left, right, context)? {
                    return Ok(false);
                }
            }
            Ok(true)
        }
        (TreeValue::Tagged(left_tag, left), TreeValue::Tagged(right_tag, right)) => {
            context
                .processing
                .work(left_tag.len().saturating_add(right_tag.len()), context.phase)?;
            Ok(left_tag == right_tag && merge_semantic_eq(left, right, context)?)
        }
        (TreeValue::String(left), TreeValue::String(right)) | (TreeValue::Number(left), TreeValue::Number(right)) => {
            context
                .processing
                .work(left.len().saturating_add(right.len()), context.phase)?;
            Ok(left == right)
        }
        _ => Ok(left.value == right.value),
    }
}

fn merge_delta_inner(
    raw: &TreeNode,
    before: &TreeNode,
    after: &TreeNode,
    path: &FieldPath,
    fields: &[FieldCapability],
    resolutions: &[FieldEdit],
    context: BudgetedMergeContext<'_>,
) -> Result<TreeNode, Finding> {
    context.tick()?;
    if merge_semantic_eq(before, after, context)?
        || resolutions.iter().any(|edit| {
            let edited = match edit {
                FieldEdit::Set { path, .. } | FieldEdit::Remove { path } => path,
            };
            edited.0.len() <= path.0.len() && path.0.starts_with(&edited.0)
        })
    {
        return context.copy(raw);
    }
    match (&before.value, &after.value, &raw.value) {
        (TreeValue::Mapping(_), TreeValue::Mapping(_), TreeValue::Mapping(_)) => {
            merge_mapping(raw, before, after, path, fields, resolutions, context)
        }
        (TreeValue::Sequence(before_items), TreeValue::Sequence(after_items), TreeValue::Sequence(raw_items)) => {
            if let MergeStrategy::MapList { keys } = strategy(path, fields) {
                if keys.is_empty() {
                    return Err(conflict().at_path(path.clone()));
                }
                let old = keyed(before_items, keys, path, context)?;
                let raw = keyed(raw_items, keys, path, context)?;
                let new = keyed(after_items, keys, path, context)?;
                for (key, previous) in &old {
                    context.tick()?;
                    if !new.contains_key(key) {
                        if let Some(original) = raw.get(key) {
                            if unknown_descendants(original, previous, context)? {
                                return Err(conflict().at_path(path.clone()));
                            }
                        }
                    }
                }
                context
                    .processing
                    .payload_array::<TreeNode>(after_items.len(), context.phase)?;
                let mut out = Vec::new();
                for (index, node) in after_items.iter().enumerate() {
                    context.tick()?;
                    let key = list_key(node, keys, path, context)?;
                    if let (Some(before), Some(original)) = (old.get(&key), raw.get(&key)) {
                        out.push(merge_delta_inner(
                            original,
                            before,
                            node,
                            &path.child(index.to_string()),
                            fields,
                            resolutions,
                            context,
                        )?);
                    } else {
                        out.push(context.copy(node)?);
                    }
                }
                // Validation of duplicate keys above is independent of reordering/removal.
                let _ = keyed(&out, keys, path, context)?;
                Ok(TreeNode {
                    value: TreeValue::Sequence(out),
                    start: raw_items.first().and_then(|n| n.start),
                })
            } else if unknown_descendants(raw, before, context)? {
                Err(conflict().at_path(path.clone()))
            } else {
                context.copy(after)
            }
        }
        _ if unknown_descendants(raw, before, context)? => Err(conflict().at_path(path.clone())),
        _ => context.copy(after),
    }
}
fn merge_mapping(
    raw: &TreeNode,
    before: &TreeNode,
    after: &TreeNode,
    path: &FieldPath,
    fields: &[FieldCapability],
    resolutions: &[FieldEdit],
    context: BudgetedMergeContext<'_>,
) -> Result<TreeNode, Finding> {
    let (Some(before_entries), Some(after_entries)) = (before.as_mapping(), after.as_mapping()) else {
        return Err(conflict());
    };
    let mut out = context.copy(raw)?;
    for (key, old) in before_entries {
        context.tick()?;
        if let Some(new) = context.get(after, key)? {
            let original = context.get(raw, key)?.unwrap_or(old);
            context.set_child(
                &mut out,
                key,
                Some(merge_delta_inner(
                    original,
                    old,
                    new,
                    &path.child(key),
                    fields,
                    resolutions,
                    context,
                )?),
            )?;
        } else {
            let child = path.child(key);
            let explicit = resolutions.iter().any(|edit| {
                let edit = match edit {
                    FieldEdit::Set { path, .. } | FieldEdit::Remove { path } => path,
                };
                child.0.starts_with(&edit.0)
            });
            if let Some(raw) = context.get(raw, key)? {
                if unknown_descendants(raw, old, context)? && !explicit {
                    return Err(conflict().at_path(child));
                }
            }
            context.set_child(&mut out, key, None)?;
        }
    }
    for (key, new) in after_entries {
        context.tick()?;
        if context.get(before, key)?.is_none() {
            context.set_child(&mut out, key, Some(context.copy(new)?))?;
        }
    }
    Ok(out)
}

fn list_key(
    node: &TreeNode,
    keys: &[&str],
    path: &FieldPath,
    context: BudgetedMergeContext<'_>,
) -> Result<Vec<String>, Finding> {
    context.tick()?;
    let tcp = port_tcp_rule(path, context.native.gvk, context.native.target);
    let service_tcp = tcp && context.native.gvk.is_some_and(|gvk| gvk.kind == "Service");
    if tcp {
        let port_key = if keys == ["port", "protocol"] {
            "port"
        } else if keys == ["containerPort", "protocol"] {
            "containerPort"
        } else {
            return Err(conflict().at_path(path.clone()));
        };
        let valid_port = context.get(node, port_key)?.is_some_and(|node| matches!(&node.value, TreeValue::Number(number) if number.parse::<i32>().is_ok_and(|port| (1..=65535).contains(&port))));
        let valid_protocol = context.get(node, "protocol")?.is_none_or(|node| {
            node.as_str().is_some_and(|protocol| {
                matches!(protocol, "TCP" | "UDP" | "SCTP") || (service_tcp && protocol.is_empty())
            })
        });
        if !valid_port || !valid_protocol {
            return Err(conflict().at_path(path.clone()));
        }
    }
    keys.iter()
        .map(|key| {
            context.tick()?;
            let Some(node) = context.get(node, key)? else {
                return if tcp && *key == "protocol" {
                    context.processing.payload(5, context.phase)?;
                    Ok(String::from("\"TCP\""))
                } else {
                    Err(conflict().at_path(path.clone()))
                };
            };
            if service_tcp && *key == "protocol" && node.as_str() == Some("") {
                context.processing.payload(5, context.phase)?;
                return Ok(String::from("\"TCP\""));
            }
            if matches!(
                node.value,
                TreeValue::Mapping(_) | TreeValue::Sequence(_) | TreeValue::Null | TreeValue::Tagged(..)
            ) {
                return Err(conflict());
            }
            let mut text = String::new();
            bounded_json(node, &mut text, context.processing)?;
            Ok(text)
        })
        .collect()
}
fn keyed<'a>(
    items: &'a [TreeNode],
    keys: &[&str],
    path: &FieldPath,
    context: BudgetedMergeContext<'_>,
) -> Result<BTreeMap<Vec<String>, &'a TreeNode>, Finding> {
    context
        .processing
        .payload_array::<(Vec<String>, &TreeNode)>(items.len(), context.phase)?;
    let mut out = BTreeMap::new();
    for node in items {
        if out.insert(list_key(node, keys, path, context)?, node).is_some() {
            return Err(conflict().at_path(path.clone()));
        }
    }
    Ok(out)
}
fn set_child(node: &mut TreeNode, key: &str, value: Option<TreeNode>) -> Result<(), Finding> {
    let TreeValue::Mapping(entries) = &mut node.value else {
        return Err(conflict());
    };
    if let Some(index) = entries.iter().position(|(k, _)| k == key) {
        if let Some(value) = value {
            entries[index].1 = value;
        } else {
            entries.remove(index);
        }
    } else if let Some(value) = value {
        entries.push((key.to_owned(), value));
    }
    Ok(())
}
pub(crate) fn json(node: &TreeNode, out: &mut String) -> Result<(), Finding> {
    match &node.value {
        TreeValue::Null => out.push_str("null"),
        TreeValue::Bool(value) => out.push_str(if *value { "true" } else { "false" }),
        TreeValue::Number(value) => out.push_str(value),
        TreeValue::String(value) => out.push_str(&serde_json::to_string(value).map_err(|_| conflict())?),
        TreeValue::Sequence(items) => {
            out.push('[');
            for (index, item) in items.iter().enumerate() {
                if index > 0 {
                    out.push(',');
                }
                json(item, out)?;
            }
            out.push(']');
        }
        TreeValue::Mapping(entries) => {
            out.push('{');
            let mut entries: Vec<_> = entries.iter().collect();
            entries.sort_by(|(a, _), (b, _)| a.cmp(b));
            let mut seen = BTreeSet::new();
            for (index, (key, value)) in entries.into_iter().enumerate() {
                if !seen.insert(key) {
                    return Err(conflict());
                }
                if index > 0 {
                    out.push(',');
                }
                out.push_str(&serde_json::to_string(key).map_err(|_| conflict())?);
                out.push(':');
                json(value, out)?;
            }
            out.push('}');
        }
        TreeValue::Tagged(..) => return Err(Finding::error(FindingCode::UnsupportedScalar, Phase::Generation)),
    }
    Ok(())
}

/// Direct merge tests select their own explicit default operation; production must
/// use `merge_native_delta_in` with the existing effective-projection operation.
#[cfg(test)]
pub(crate) fn merge_native_delta(
    raw: &TreeNode,
    before: &TreeNode,
    after: &TreeNode,
    path: &FieldPath,
    fields: &[FieldCapability],
    resolutions: &[FieldEdit],
    context: MergeContext<'_>,
) -> Result<TreeNode, Finding> {
    let processing = NativeOperationBudget::new(NativeProcessingLimits::default());
    merge_native_delta_in(
        raw,
        before,
        after,
        path,
        fields,
        resolutions,
        BudgetedMergeContext {
            native: context,
            processing: &processing,
            phase: Phase::Generation,
        },
    )
}
/// Validate all declared map-list identities even when no semantic edit occurred.
pub(crate) fn merge_native_delta_in(
    raw: &TreeNode,
    before: &TreeNode,
    after: &TreeNode,
    path: &FieldPath,
    fields: &[FieldCapability],
    resolutions: &[FieldEdit],
    context: BudgetedMergeContext<'_>,
) -> Result<TreeNode, Finding> {
    let merged = merge_delta_inner(raw, before, after, path, fields, resolutions, context)?;
    // Explicit caller repair is applied to the charged checked view, never to immutable originals.
    let mut checked = context.copy(&merged)?;
    for edit in resolutions {
        context.tick()?;
        let (edited, value) = match edit {
            FieldEdit::Set { path, value } => (path, Some(value)),
            FieldEdit::Remove { path } => (path, None),
        };
        if edited.0.starts_with(&path.0) {
            let segments = &edited.0[path.0.len()..];
            context
                .processing
                .payload_sizes(segments.iter().map(String::len), context.phase)?;
            context
                .processing
                .payload_array::<String>(segments.len(), context.phase)?;
            let relative = FieldPath(segments.to_vec());
            if relative.0.is_empty() {
                checked = if let Some(value) = value {
                    context.copy(value)?
                } else {
                    TreeNode::new(TreeValue::Null)
                };
            } else {
                apply_edit_value_in(&mut checked, &relative, value, context)?;
            }
        } else if path.0.starts_with(&edited.0) {
            checked = TreeNode::new(TreeValue::Null);
        }
    }
    check_supplied_list_duplicates(&checked, path, fields, context)?;
    Ok(merged)
}

#[cfg(test)]
pub(crate) fn merge_delta(
    raw: &TreeNode,
    before: &TreeNode,
    after: &TreeNode,
    path: &FieldPath,
    fields: &[FieldCapability],
    resolutions: &[FieldEdit],
) -> Result<TreeNode, Finding> {
    merge_native_delta(
        raw,
        before,
        after,
        path,
        fields,
        resolutions,
        MergeContext {
            gvk: None,
            target: None,
        },
    )
}
fn check_supplied_list_duplicates(
    tree: &TreeNode,
    path: &FieldPath,
    fields: &[FieldCapability],
    context: BudgetedMergeContext<'_>,
) -> Result<(), Finding> {
    context.tick()?;
    match &tree.value {
        TreeValue::Sequence(items) => {
            if let MergeStrategy::MapList { keys } = strategy(path, fields) {
                let mut seen = BTreeSet::new();
                for item in items {
                    // Preserve malformed unchanged source values for exact native validation.
                    // Every valid key is still scanned, including those after malformed siblings.
                    context.tick()?;
                    let key = list_key(item, keys, path, context);
                    if context.processing.exhausted() {
                        return Err(context.processing.fail(context.phase));
                    }
                    if let Ok(key) = key {
                        if !seen.insert(key) {
                            return Err(conflict().at_path(path.clone()));
                        }
                    }
                }
            }
            for (index, item) in items.iter().enumerate() {
                context.tick()?;
                check_supplied_list_duplicates(item, &path.child(index.to_string()), fields, context)?;
            }
        }
        TreeValue::Mapping(entries) => {
            for (key, node) in entries {
                context.tick()?;
                check_supplied_list_duplicates(node, &path.child(key), fields, context)?;
            }
        }
        _ => {}
    }
    Ok(())
}
fn port_tcp_rule(
    path: &FieldPath,
    gvk: Option<&crate::model::GroupVersionKind>,
    target: Option<&TargetProfile>,
) -> bool {
    let Some(gvk) = gvk else {
        return false;
    };
    if target.is_some_and(|target| {
        declaration(gvk)
            .is_none_or(|declaration| !(declaration.first..=declaration.last).contains(&target.kubernetes.minor()))
    }) {
        return false;
    }
    let prefix = match (gvk.group.as_deref(), gvk.version.as_str(), gvk.kind.as_str()) {
        (None, "v1", "Service") => return path.0 == ["spec", "ports"],
        (None, "v1", "Pod") => "/spec",
        (None, "v1", "ReplicationController")
        | (Some("apps"), "v1", "Deployment" | "StatefulSet" | "DaemonSet" | "ReplicaSet")
        | (Some("batch"), "v1", "Job") => "/spec/template/spec",
        (Some("batch"), "v1" | "v1beta1", "CronJob") => "/spec/jobTemplate/spec/template/spec",
        _ => return false,
    };
    let Ok(prefix) = FieldPath::parse(prefix) else {
        return false;
    };
    path.0.len() == prefix.0.len() + 3
        && path.0.starts_with(&prefix.0)
        && matches!(path.0[prefix.0.len()].as_str(), "containers" | "initContainers")
        && (path.0[prefix.0.len() + 1] == "*" || path.0[prefix.0.len() + 1].parse::<usize>().is_ok())
        && path.0[prefix.0.len() + 2] == "ports"
}

#[derive(Clone, Copy)]
pub(crate) struct MergeContext<'a> {
    pub(crate) gvk: Option<&'a crate::model::GroupVersionKind>,
    pub(crate) target: Option<&'a TargetProfile>,
}

/// Private effective-reprojection policy and its existing shared operation.
#[derive(Clone, Copy)]
pub(crate) struct BudgetedMergeContext<'a> {
    pub(crate) native: MergeContext<'a>,
    pub(crate) processing: &'a NativeOperationBudget,
    pub(crate) phase: Phase,
}
impl BudgetedMergeContext<'_> {
    fn tick(self) -> Result<(), Finding> {
        self.processing.work(1, self.phase)
    }
    fn copy(self, node: &TreeNode) -> Result<TreeNode, Finding> {
        self.processing.tree_copy(node, self.phase)?;
        Ok(node.clone())
    }
    fn set_child(self, node: &mut TreeNode, key: &str, value: Option<TreeNode>) -> Result<(), Finding> {
        self.tick()?;
        let TreeValue::Mapping(entries) = &mut node.value else {
            return Err(conflict());
        };
        let mut found = None;
        for (index, (name, _)) in entries.iter().enumerate() {
            self.tick()?;
            self.processing.work(name.len().saturating_add(key.len()), self.phase)?;
            if name == key {
                found = Some(index);
                break;
            }
        }
        match (found, value) {
            (Some(index), Some(value)) => entries[index].1 = value,
            (Some(index), None) => {
                self.processing.work(entries.len() - index, self.phase)?;
                entries.remove(index);
            }
            (None, Some(value)) => {
                self.processing
                    .payload_sizes([key.len(), size_of::<(String, TreeNode)>()], self.phase)?;
                entries.push((key.to_owned(), value));
            }
            (None, None) => {}
        }
        Ok(())
    }
    fn get<'a>(self, node: &'a TreeNode, key: &str) -> Result<Option<&'a TreeNode>, Finding> {
        if let Some(entries) = node.as_mapping() {
            for (name, value) in entries {
                self.tick()?;
                self.processing.work(name.len().saturating_add(key.len()), self.phase)?;
                if name == key {
                    return Ok(Some(value));
                }
            }
        }
        Ok(None)
    }
}
/// Apply a retained edit without resetting the caller's operation or cloning before preflight.
pub(crate) fn apply_edit_in(
    tree: &mut TreeNode,
    edit: &FieldEdit,
    processing: &NativeOperationBudget,
    phase: Phase,
) -> Result<(), Finding> {
    let (path, value) = match edit {
        FieldEdit::Set { path, value } => (path, Some(value)),
        FieldEdit::Remove { path } => (path, None),
    };
    apply_edit_value_in(
        tree,
        path,
        value,
        BudgetedMergeContext {
            native: MergeContext {
                gvk: None,
                target: None,
            },
            processing,
            phase,
        },
    )
}
fn apply_edit_value_in(
    tree: &mut TreeNode,
    path: &FieldPath,
    value: Option<&TreeNode>,
    context: BudgetedMergeContext<'_>,
) -> Result<(), Finding> {
    context.tick()?;
    let value = value.map(|value| context.copy(value)).transpose()?;
    let Some((last, parents)) = path.0.split_last() else {
        return Err(conflict().at_path(path.clone()));
    };
    let mut node = tree;
    for parent in parents {
        context.tick()?;
        match &mut node.value {
            TreeValue::Mapping(entries) => {
                let mut found = None;
                for (index, (key, _)) in entries.iter().enumerate() {
                    context.tick()?;
                    if key == parent {
                        found = Some(index);
                        break;
                    }
                }
                let Some(index) = found else {
                    return Err(conflict().at_path(path.clone()));
                };
                node = &mut entries[index].1;
            }
            TreeValue::Sequence(items) => {
                let index = parent.parse::<usize>().map_err(|_| conflict())?;
                node = items.get_mut(index).ok_or_else(conflict)?;
            }
            _ => return Err(conflict().at_path(path.clone())),
        }
    }
    if let TreeValue::Sequence(items) = &mut node.value {
        let index = last.parse::<usize>().map_err(|_| conflict())?;
        if index >= items.len() {
            return Err(conflict());
        }
        if let Some(value) = value {
            items[index] = value;
        } else {
            items.remove(index);
        }
        Ok(())
    } else {
        if let Some(entries) = node.as_mapping() {
            context.processing.work(entries.len(), context.phase)?;
        }
        context.processing.payload(last.len(), context.phase)?;
        set_child(node, last, value)
    }
}

fn observation_node<'a>(
    tree: &'a TreeNode,
    path: &FieldPath,
    processing: &NativeOperationBudget,
) -> Result<Option<&'a TreeNode>, Finding> {
    let context = BudgetedMergeContext {
        native: MergeContext {
            gvk: None,
            target: None,
        },
        processing,
        phase: Phase::Generation,
    };
    let mut current = Some(tree);
    for part in &path.0 {
        current = match current {
            Some(node) if node.as_mapping().is_some() => context.get(node, part)?,
            Some(node) => {
                processing.work(part.len().saturating_add(1), Phase::Generation)?;
                node.as_sequence()
                    .and_then(|items| part.parse::<usize>().ok().and_then(|index| items.get(index)))
            }
            None => None,
        };
    }
    Ok(current)
}

fn apply_observation_output(
    doc: &crate::model::ResourceDocument,
    tree: &mut TreeNode,
    mut observations: Vec<crate::source::ObservationPath>,
    options: &GenerationOptions,
    findings: &mut ProcessingReport,
    processing: &NativeOperationBudget,
) -> Result<(), Finding> {
    let topology = topology_observation_paths(doc, tree, processing)?;
    if options.intent == OutputIntent::AuthoredIntent {
        processing.payload_array::<crate::source::ObservationPath>(topology.len(), Phase::Generation)?;
        observations.extend(topology.into_iter().map(|path| crate::source::ObservationPath {
            path,
            role: crate::source::ObservationRole::ServerOwned,
        }));
        strip_observation_paths(tree, Some(doc.id), &observations, findings);
    } else if options.opaque_fields == OpaqueFieldPolicy::PreserveWithFinding
        && options.protected_output == ProtectedOutput::Include
        && doc.evidence.origin != crate::source::EvidenceOrigin::NativeAuthored
        && !topology.is_empty()
    {
        for path in &topology {
            processing.work(path.0.len(), Phase::Generation)?;
            let Some((original, effective)) =
                observation_node(&doc.original, path, processing)?.zip(observation_node(tree, path, processing)?)
            else {
                return Ok(());
            };
            if !same_observation_payload(original, effective, processing)? {
                return Ok(());
            }
        }
        for finding in findings.entries_mut() {
            processing.work(1, Phase::Generation)?;
            if finding.resource == Some(doc.id) && finding.code == FindingCode::UnadmittedField {
                if let Some(path) = &finding.path {
                    processing.work(
                        topology.iter().fold(1_usize, |total, observation| {
                            total
                                .saturating_add(observation.0.iter().map(String::len).sum::<usize>())
                                .saturating_add(path.0.iter().map(String::len).sum::<usize>())
                                .saturating_add(path.0.len())
                        }),
                        Phase::Generation,
                    )?;
                    if path.0 == ["endpoints", "*", "deprecatedTopology"]
                        || topology.iter().any(|observation| path.0.starts_with(&observation.0))
                    {
                        finding.severity = Severity::Warning;
                    }
                }
            }
        }
    }
    processing.work(0, Phase::Generation)
}
fn topology_observation_paths(
    document: &crate::model::ResourceDocument,
    tree: &TreeNode,
    processing: &NativeOperationBudget,
) -> Result<Vec<FieldPath>, Finding> {
    let identity = &document.original_identity;
    if identity.gvk.group.as_deref() != Some("discovery.k8s.io")
        || identity.gvk.version != "v1"
        || identity.gvk.kind != "EndpointSlice"
    {
        return Ok(Vec::new());
    }
    let Some(capability) = &document.capability else {
        return Ok(Vec::new());
    };
    processing.work(capability.fields.len(), Phase::Generation)?;
    if !capability
        .fields
        .iter()
        .any(|field| field.path == "/endpoints/*/deprecatedTopology" && field.admission == FieldAdmission::PreserveOnly)
    {
        return Ok(Vec::new());
    }
    let mut paths = Vec::new();
    let lookup = BudgetedMergeContext {
        native: MergeContext {
            gvk: None,
            target: None,
        },
        processing,
        phase: Phase::Generation,
    };
    if let Some(endpoints) = lookup.get(tree, "endpoints")?.and_then(TreeNode::as_sequence) {
        for (index, endpoint) in endpoints.iter().enumerate() {
            processing.work(
                endpoint.as_mapping().map_or(1, |values| values.len().saturating_add(1)),
                Phase::Generation,
            )?;
            if lookup.get(endpoint, "deprecatedTopology")?.is_some() {
                processing.payload_array::<FieldPath>(1, Phase::Generation)?;
                processing.payload_array::<String>(3, Phase::Generation)?;
                processing.payload(47, Phase::Generation)?;
                paths.push(FieldPath(vec![
                    "endpoints".into(),
                    index.to_string(),
                    "deprecatedTopology".into(),
                ]));
            }
        }
    }
    Ok(paths)
}
fn same_observation_payload(
    left: &TreeNode,
    right: &TreeNode,
    processing: &NativeOperationBudget,
) -> Result<bool, Finding> {
    processing.work(1, Phase::Generation)?;
    match (&left.value, &right.value) {
        (TreeValue::Mapping(left), TreeValue::Mapping(right)) => {
            if left.len() != right.len() {
                return Ok(false);
            }
            processing.payload_array::<(&str, &TreeNode)>(right.len(), Phase::Generation)?;
            for (key, _) in right {
                processing.work(
                    key.len()
                        .saturating_add(1)
                        .saturating_mul(right.len().saturating_add(1)),
                    Phase::Generation,
                )?;
            }
            let indexed: BTreeMap<&str, &TreeNode> = right.iter().map(|(key, value)| (key.as_str(), value)).collect();
            for (key, value) in left {
                processing.work(
                    key.len()
                        .saturating_add(1)
                        .saturating_mul(right.len().saturating_add(1)),
                    Phase::Generation,
                )?;
                let Some(other) = indexed.get(key.as_str()) else {
                    return Ok(false);
                };
                if !same_observation_payload(value, other, processing)? {
                    return Ok(false);
                }
            }
            Ok(true)
        }
        (TreeValue::Sequence(left), TreeValue::Sequence(right)) => {
            if left.len() != right.len() {
                return Ok(false);
            }
            for (left, right) in left.iter().zip(right) {
                if !same_observation_payload(left, right, processing)? {
                    return Ok(false);
                }
            }
            Ok(true)
        }
        (TreeValue::String(left), TreeValue::String(right)) | (TreeValue::Number(left), TreeValue::Number(right)) => {
            processing.work(left.len().saturating_add(right.len()), Phase::Generation)?;
            Ok(left == right)
        }
        (TreeValue::Tagged(left_tag, left), TreeValue::Tagged(right_tag, right)) => {
            processing.work(left_tag.len().saturating_add(right_tag.len()), Phase::Generation)?;
            Ok(left_tag == right_tag && same_observation_payload(left, right, processing)?)
        }
        (TreeValue::Bool(left), TreeValue::Bool(right)) => Ok(left == right),
        (TreeValue::Null, TreeValue::Null) => Ok(true),
        _ => Ok(false),
    }
}

#[cfg(test)]
mod merge_processing_tests {
    use super::*;

    #[test]
    fn newly_inserted_mapping_keys_preflight_payload_before_copy() -> Result<(), String> {
        let key = "private-new-key".repeat(1024);
        let raw = TreeNode::new(TreeValue::Mapping(Vec::new()));
        let before = TreeNode::new(TreeValue::Mapping(Vec::new()));
        let after = TreeNode::new(TreeValue::Mapping(vec![(key.clone(), TreeNode::new(TreeValue::Null))]));
        let merge = |processing: &NativeOperationBudget| {
            merge_native_delta_in(
                &raw,
                &before,
                &after,
                &FieldPath::default(),
                &[],
                &[],
                BudgetedMergeContext {
                    native: MergeContext {
                        gvk: None,
                        target: None,
                    },
                    processing,
                    phase: Phase::Generation,
                },
            )
        };
        // One key copy plus the small fixed nodes fits. Retaining both the inserted
        // key and the checked view requires two key copies, independently of codec work.
        let lowered = NativeOperationBudget::new(NativeProcessingLimits {
            max_payload_bytes: key.len() + 1024,
            ..NativeProcessingLimits::default()
        });
        let Err(finding) = merge(&lowered) else {
            return Err("unreserved insertion key unexpectedly fit".into());
        };
        assert_eq!(finding.code, FindingCode::LimitExceeded);
        assert!(finding.path.is_none());
        assert!(!format!("{finding:?}").contains("private-new-key"));
        assert!(lowered.exhausted());
        let control = merge(&NativeOperationBudget::new(NativeProcessingLimits::default()))
            .map_err(|_| "control merge failed")?;
        assert!(
            control
                .get(&key)
                .is_some_and(|node| matches!(node.value, TreeValue::Null))
        );
        assert!(raw.as_mapping().is_some_and(<[_]>::is_empty));
        assert!(before.as_mapping().is_some_and(<[_]>::is_empty));
        Ok(())
    }

    #[test]
    fn native_pod_reprojection_preflights_raw_and_checked_opaque_copies() -> Result<(), String> {
        let private = "private-opaque-root".repeat(2048);
        let text = format!(
            "apiVersion: v1\nkind: Pod\nmetadata: {{name: merge}}\nspec:\n  containers: [{{name: main, image: example.invalid/app:v1}}]\nretainedOpaque: {private}\n"
        );
        let resources = parsed_resources(&text)?;
        let document = resources.documents.first().ok_or("missing Pod")?;
        assert!(document.resource::<crate::resources::workloads::Pod>().is_some());
        let native = document.resource.as_ref().ok_or("missing native Pod")?;
        let before = document.original_known.as_ref().ok_or("missing original codec tree")?;
        let target = TargetProfile::documented_defaults(
            crate::capability::KubernetesVersion::new(1, 30).map_err(|_| "target failed")?,
        );
        let prefix_fits = |bytes, copies| codec_prefix_fits(document, &target, bytes, copies);
        for copies in [0, 1] {
            let (mut low, mut high) = (0, 1_000_000);
            assert!(prefix_fits(high, copies));
            while low < high {
                let middle = low + (high - low) / 2;
                if prefix_fits(middle, copies) {
                    high = middle;
                } else {
                    low = middle + 1;
                }
            }
            let allowance = low.checked_add(private.len() / 2).ok_or("allowance overflow")?;
            assert!(prefix_fits(allowance, copies));
            let processing = operation(allowance);
            let context = crate::registry::EncodeContext::in_operation(
                Some(&target),
                *document.evidence.limits(),
                processing.clone(),
            );
            let known = crate::registry::encode_in(native.as_ref(), &context).map_err(|_| "encoding did not fit")?;
            crate::model::identity_in(&known, document.original_identity.scope, &processing, Phase::Generation)
                .map_err(|_| "identity did not fit")?;
            let error = merge_native_delta_in(
                &document.original,
                before,
                &known,
                &FieldPath::default(),
                document.capability.as_ref().map_or(&[], |capability| capability.fields),
                &[],
                BudgetedMergeContext {
                    native: MergeContext {
                        gvk: Some(&document.original_identity.gvk),
                        target: Some(&target),
                    },
                    processing: &processing,
                    phase: Phase::Generation,
                },
            )
            .err()
            .ok_or("uncharged opaque merge copy")?;
            assert_eq!(error.code, FindingCode::LimitExceeded);
            assert!(error.path.is_none());
            let context = crate::registry::EncodeContext::in_operation(
                Some(&target),
                *document.evidence.limits(),
                operation(allowance),
            );
            let error = document
                .current_tree_in(Some(&target), Some(&context))
                .err()
                .ok_or("effective tree bypassed merge budget")?;
            assert_eq!(error.code, FindingCode::LimitExceeded);
            assert!(error.path.is_none());
        }
        let context = crate::registry::EncodeContext::in_operation(
            Some(&target),
            *document.evidence.limits(),
            operation(1_000_000),
        );
        let tree = document
            .current_tree_in(Some(&target), Some(&context))
            .map_err(|_| "control merge failed")?;
        assert_eq!(
            tree.get("retainedOpaque").and_then(TreeNode::as_str),
            Some(private.as_str())
        );
        assert_eq!(
            document
                .source_evidence()
                .reveal_raw(&crate::source::ExplicitSourceAccess::explicitly_allow_raw_source()),
            text.as_bytes()
        );
        Ok(())
    }
    fn parsed_resources(text: &str) -> Result<ResourceSet, String> {
        let input = crate::parse_source(
            crate::source::SourceInput {
                id: crate::source::SourceId(41),
                format: crate::source::DocumentFormat::YamlStream,
                origin: crate::source::InputOrigin::Authored,
                source_version: None,
                bytes: text.as_bytes(),
            },
            &crate::source::ParseLimits::default(),
        )
        .map_err(|_| "parse failed")?;
        input.flatten_resources().map_err(|_| "flatten failed".into())
    }
    fn operation(bytes: usize) -> NativeOperationBudget {
        NativeOperationBudget::new(NativeProcessingLimits {
            max_payload_bytes: bytes,
            ..NativeProcessingLimits::default()
        })
    }
    fn codec_prefix_fits(
        document: &crate::model::ResourceDocument,
        target: &TargetProfile,
        bytes: usize,
        copies: usize,
    ) -> bool {
        let processing = operation(bytes);
        let context =
            crate::registry::EncodeContext::in_operation(Some(target), *document.evidence.limits(), processing.clone());
        let Some(native) = &document.resource else {
            return false;
        };
        let Ok(known) = crate::registry::encode_in(native.as_ref(), &context) else {
            return false;
        };
        if crate::model::identity_in(&known, document.original_identity.scope, &processing, Phase::Generation).is_err()
        {
            return false;
        }
        // Effective known encoding excludes the opaque root. Its preservation
        // belongs to the merge, so this probe cannot fail while encoding that value.
        assert!(known.get("retainedOpaque").is_none());
        (0..copies).all(|_| processing.tree_copy(&document.original, Phase::Generation).is_ok())
    }
}

#[cfg(test)]
mod access_mode_occurrence_tests {
    use super::*;
    use crate::source::{DocumentFormat, InputOrigin, ParseLimits, SourceId, SourceInput};
    #[test]
    fn ambiguous_or_positionless_ancestor_occurrences_cannot_authorize_preservation() -> Result<(), String> {
        // A synthetic preservation-only root isolates occurrence proof from duplicate
        // native names and other owning-resource validation rules.
        let bytes = br#"{"apiVersion":"v1","kind":"PersistentVolume","metadata":{"name":"sample"},"spec":{"templates":[{"accessModes":["private"]},{"accessModes":["private"]}]}}"#;
        let resources = crate::parse_source(
            SourceInput {
                id: SourceId(12),
                format: DocumentFormat::Json,
                origin: InputOrigin::CallerSupplied,
                source_version: None,
                bytes,
            },
            &ParseLimits::default(),
        )
        .map_err(|_| "parse occurrence fixture")?
        .flatten_resources()
        .map_err(|_| "flatten occurrence fixture")?;
        let document = resources.documents().first().ok_or("missing occurrence root")?;
        let path = FieldPath::parse("/spec/templates/0/accessModes").map_err(|_| "path")?;
        let proof = |tree: &TreeNode| {
            supplied_access_mode_occurrence(
                document,
                tree,
                &crate::syntax::NativeOccurrences::new(),
                &path,
                &NativeOperationBudget::new(NativeProcessingLimits::default()),
            )
            .map_err(|_| "occurrence budget".to_owned())
        };
        assert!(proof(&document.original)?);
        for ambiguous in [true, false] {
            let mut tree = document.original.clone();
            let TreeValue::Mapping(root) = &mut tree.value else {
                return Err("root map".into());
            };
            let spec = root.iter_mut().find(|(key, _)| key == "spec").ok_or("spec")?;
            let TreeValue::Mapping(spec) = &mut spec.1.value else {
                return Err("spec map".into());
            };
            let templates = spec.iter_mut().find(|(key, _)| key == "templates").ok_or("templates")?;
            let TreeValue::Sequence(items) = &mut templates.1.value else {
                return Err("templates array".into());
            };
            if ambiguous {
                items[1].start = items[0].start;
            } else {
                items[0].start = None;
            }
            assert!(!proof(&tree)?);
        }
        Ok(())
    }
}
