//! Deterministic private in-memory output and merge-safe live typed deltas.
use crate::{
    capability::{FeatureGateState, FieldAdmission, FieldCapability, MergeStrategy, TargetProfile, declaration},
    diagnostic::{FieldPath, Finding, FindingCode, Phase, ResourceId, Severity, WrapperSubject, has_errors},
    model::{FieldEdit, ResourceSet},
    registry::ValidationContext,
    syntax::{TreeNode, TreeValue},
};
use std::{
    collections::{BTreeMap, BTreeSet},
    fmt,
    sync::Arc,
};
/// Explicit output syntax.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OutputFormat {
    /// Deterministic YAML document stream.
    Yaml,
    /// Strict deterministic JSON.
    Json,
}
/// Explicit JSON collection shape.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum JsonShape {
    /// Exactly one native document.
    SingleResource,
    /// A generic Kubernetes List.
    KubernetesList,
}
/// Explicit native validation operation; never inferred from source or output origin.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum NativeValidationIntent {
    /// Operation-dependent rules remain unverified and produce safe findings.
    #[default]
    Unspecified,
    /// Validate the reviewed create-specific rules, without executing a request.
    Create,
}
/// Native source intent independent of source origin.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OutputIntent {
    /// Retain supplied observations under the same target/opaque/protected checks.
    PreserveObservation,
    /// Retain observations unless explicitly edited.
    PreserveDocument,
    /// Remove only recognized server-owned fields with findings.
    AuthoredIntent,
}
/// No synthetic placeholder output exists.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProtectedOutput {
    /// Refuse any protected/private opaque payload.
    Deny,
    /// Explicitly authorize actual native payload bytes.
    Include,
}
/// Opaque preservation is separate from typed/native admission.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OpaqueFieldPolicy {
    /// Fail when field availability cannot be established.
    Block,
    /// Explicitly preserve with unadmitted findings.
    PreserveWithFinding,
}
/// Native wrapper retention is an explicit caller decision.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CollectionOutput {
    /// Keep source List wrappers and metadata/order.
    PreserveWrappers,
    /// Emit native items in a deterministic stream.
    Flatten,
}
/// Explicit private-output, admission, and intent policies.
#[derive(Clone, Debug)]
pub struct GenerationOptions {
    /// Default denies private values.
    pub protected_output: ProtectedOutput,
    /// Default blocks opaque availability.
    pub opaque_fields: OpaqueFieldPolicy,
    /// Strict JSON shape.
    pub json_shape: JsonShape,
    /// Explicit output intent.
    pub intent: OutputIntent,
    /// Native operation context, independent of output intent and source origin.
    pub validation_intent: NativeValidationIntent,
    /// Explicit YAML/JSON collection policy.
    pub collections: CollectionOutput,
}
impl Default for GenerationOptions {
    fn default() -> Self {
        Self {
            protected_output: ProtectedOutput::Deny,
            opaque_fields: OpaqueFieldPolicy::Block,
            json_shape: JsonShape::KubernetesList,
            intent: OutputIntent::PreserveDocument,
            validation_intent: NativeValidationIntent::Unspecified,
            collections: CollectionOutput::PreserveWrappers,
        }
    }
}
/// Explicit private artifact access token.
#[derive(Clone, Copy, Debug)]
pub struct ExplicitArtifactAccess(());
impl ExplicitArtifactAccess {
    /// Deliberately authorize raw generated bytes.
    #[must_use]
    pub const fn explicitly_allow_raw_artifact() -> Self {
        Self(())
    }
}
/// Generated bytes remain private and do not imply compatibility or deployment.
pub struct GeneratedArtifact {
    format: OutputFormat,
    bytes: Arc<[u8]>,
    findings: Vec<Finding>,
}
impl GeneratedArtifact {
    /// Selected syntax.
    #[must_use]
    pub const fn format(&self) -> OutputFormat {
        self.format
    }
    /// Structured outcomes, never source values.
    #[must_use]
    pub fn findings(&self) -> &[Finding] {
        &self.findings
    }
    /// Reveal native bytes only after explicit authorization.
    #[must_use]
    pub fn reveal_bytes(&self, _access: &ExplicitArtifactAccess) -> &[u8] {
        &self.bytes
    }
}
impl fmt::Debug for GeneratedArtifact {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("GeneratedArtifact")
            .field("format", &self.format)
            .field("byte_len", &self.bytes.len())
            .field("findings", &self.findings)
            .finish_non_exhaustive()
    }
}
fn validate_wrapper(list: &crate::model::ListDocument, target: &TargetProfile, findings: &mut Vec<Finding>) {
    if let Some(metadata) = list.original.get("metadata") {
        if let Some(entries) = metadata.as_mapping() {
            for (key, node) in entries {
                let valid = match key.as_str() {
                    "resourceVersion" | "selfLink" | "continue" => {
                        matches!(node.value, TreeValue::String(_) | TreeValue::Null)
                    }
                    "remainingItemCount" => {
                        matches!(&node.value, TreeValue::Number(value) if value.parse::<u64>().is_ok())
                            || node.value == TreeValue::Null
                    }
                    _ => true,
                };
                if !valid {
                    findings.push(wrapper_finding(
                        list,
                        FindingCode::NativeFieldInvalid,
                        Phase::Validation,
                        FieldPath(vec!["metadata".into(), key.clone()]),
                        true,
                    ));
                }
            }
        } else {
            findings.push(wrapper_finding(
                list,
                FindingCode::NativeFieldInvalid,
                Phase::Validation,
                FieldPath(vec!["metadata".into()]),
                true,
            ));
        }
    }
    let Ok(mut gvk) = crate::model::tree_gvk(&list.original) else {
        return;
    };
    if gvk.group.is_none() && gvk.version == "v1" && gvk.kind == "List" {
        return;
    }
    if let Some(kind) = gvk.kind.strip_suffix("List") {
        gvk.kind = kind.to_owned();
    }
    if declaration(&gvk).is_some_and(|decl| !(decl.first..=decl.last).contains(&target.kubernetes.minor()))
        || declaration(&gvk).is_none() && crate::capability::builtin_scope(&gvk).is_some()
    {
        findings.push(wrapper_finding(
            list,
            FindingCode::UnavailableApi,
            Phase::Validation,
            FieldPath::default(),
            true,
        ));
    }
    findings.extend(
        crate::capability::source_field_findings(&list.original, &gvk, target)
            .into_iter()
            .map(|mut finding| {
                finding.wrapper = Some(WrapperSubject {
                    source: list.source,
                    list: list.id,
                });
                if finding.source.is_none() {
                    finding.source = finding
                        .path
                        .as_ref()
                        .and_then(|path| list.original.get_path(path))
                        .and_then(|node| node.start)
                        .or(list.original.start);
                }
                finding
            }),
    );
}
/// Validate current resources and every retained List against the explicit target.
#[must_use]
pub fn validate_for_target(resources: &ResourceSet, target: &TargetProfile) -> Vec<Finding> {
    validate_for_target_with_intent(resources, target, NativeValidationIntent::Unspecified)
}
/// Validate the same effective native trees with explicitly supplied operation context.
/// This does not establish API-server conformance or authorize execution.
#[must_use]
pub fn validate_for_target_with_intent(
    resources: &ResourceSet,
    target: &TargetProfile,
    intent: NativeValidationIntent,
) -> Vec<Finding> {
    let mut findings = target.findings();
    findings.extend(resources.identity_findings());
    for list in &resources.lists {
        validate_wrapper(list, target, &mut findings);
    }
    for document in &resources.documents {
        let tree = match document.current_tree(Some(target)) {
            Ok(tree) => tree,
            Err(error) => {
                if error.code == FindingCode::MergeConflict {
                    let mut native =
                        Finding::error(FindingCode::NativeFieldInvalid, Phase::Validation).for_resource(document.id);
                    native.path.clone_from(&error.path);
                    native.source = error.source;
                    findings.push(native);
                }
                findings.push(error.for_resource(document.id));
                continue;
            }
        };
        let identity = match crate::model::identity(&tree, document.original_identity.scope) {
            Ok(identity) => identity,
            Err(error) => {
                findings.push(error.for_resource(document.id));
                continue;
            }
        };
        if let Some(decl) = declaration(&identity.gvk) {
            if !(decl.first..=decl.last).contains(&target.kubernetes.minor()) {
                findings.push(Finding::error(FindingCode::UnavailableApi, Phase::Validation).for_resource(document.id));
            }
        } else if crate::capability::builtin_scope(&identity.gvk).is_some() {
            findings.push(Finding::error(FindingCode::UnavailableApi, Phase::Validation).for_resource(document.id));
        } else if identity.scope == crate::model::ResourceScope::Unknown {
            findings.push(Finding::warning(FindingCode::ScopeUnknown, Phase::Validation).for_resource(document.id));
        }
        findings.extend(
            crate::capability::source_field_findings(&tree, &identity.gvk, target)
                .into_iter()
                .map(|f| f.for_resource(document.id)),
        );
        if let Some(capability) = &document.capability {
            if target.kubernetes < capability.api_since
                || capability
                    .api_removed
                    .is_some_and(|removed| target.kubernetes >= removed)
            {
                findings.push(Finding::error(FindingCode::UnavailableApi, Phase::Validation).for_resource(document.id));
            }
            for field in capability.fields {
                if field_nodes(&tree, field.path).is_empty() {
                    continue;
                }
                let path = FieldPath::parse(field.path).ok();
                let code = if target.kubernetes < field.since
                    || field.removed.is_some_and(|removed| target.kubernetes >= removed)
                {
                    Some(FindingCode::UnavailableField)
                } else if field.feature_gate.is_some_and(|gate| {
                    target.feature_gates.resolve(gate, target.kubernetes) != Ok(FeatureGateState::Enabled)
                }) {
                    Some(FindingCode::FeatureGateRequired)
                } else if field.admission != FieldAdmission::Typed {
                    Some(FindingCode::UnadmittedField)
                } else {
                    None
                };
                if let Some(code) = code {
                    let mut f = Finding::error(code, Phase::Validation).for_resource(document.id);
                    f.path = path;
                    findings.push(f);
                }
            }
        } else {
            findings.push(
                Finding::warning(
                    if declaration(&identity.gvk).is_some() {
                        FindingCode::UnadmittedKind
                    } else {
                        FindingCode::UnknownKind
                    },
                    Phase::Validation,
                )
                .for_resource(document.id),
            );
        }
        validate_native(document, &tree, &identity, target, intent, &mut findings);
    }
    findings
}
fn validate_native(
    document: &crate::model::ResourceDocument,
    tree: &TreeNode,
    identity: &crate::model::ResourceIdentity,
    target: &TargetProfile,
    intent: NativeValidationIntent,
    findings: &mut Vec<Finding>,
) {
    if let Some(decode) = document.decode {
        match decode(
            tree,
            &document.evidence,
            &crate::registry::DecodeContext {
                gvk: &identity.gvk,
                scope: identity.scope,
            },
        ) {
            Ok(resource) => {
                let mut native = Vec::new();
                resource.validate(&ValidationContext { intent, target }, &mut native);
                findings.extend(native.into_iter().map(|finding| finding.for_resource(document.id)));
            }
            Err(errors) => findings.extend(errors.into_iter().map(|finding| finding.for_resource(document.id))),
        }
    }
}
pub(crate) fn field_nodes<'a>(tree: &'a TreeNode, pointer: &str) -> Vec<&'a TreeNode> {
    let Ok(path) = FieldPath::parse(pointer) else {
        return Vec::new();
    };
    let mut nodes = vec![tree];
    for segment in &path.0 {
        let mut next = Vec::new();
        for node in nodes {
            if segment == "*" {
                match &node.value {
                    TreeValue::Sequence(items) => next.extend(items),
                    TreeValue::Mapping(entries) => next.extend(entries.iter().map(|(_, v)| v)),
                    _ => {}
                }
            } else if let Some(value) = node.get(segment) {
                next.push(value);
            }
        }
        nodes = next;
    }
    nodes
}
/// Generate current native values without files, processes, clusters, or implicit migration.
/// # Errors
/// Blocks invalid targets/identities, unavailable APIs/fields, opaque/private output, and lossy edits.
pub fn generate(
    resources: &ResourceSet,
    target: &TargetProfile,
    format: OutputFormat,
    options: &GenerationOptions,
) -> Result<GeneratedArtifact, Vec<Finding>> {
    let mut findings = validate_for_target_with_intent(resources, target, options.validation_intent);
    let mut trees = BTreeMap::new();
    for doc in &resources.documents {
        let projection = match doc.project(Some(target)) {
            Ok(projection) => projection,
            Err(errors) => {
                findings.extend(errors);
                continue;
            }
        };
        findings.extend(projection.findings);
        let mut tree = projection.tree;
        if options.intent == OutputIntent::AuthoredIntent {
            strip_observation_paths(&mut tree, Some(doc.id), &projection.observations, &mut findings);
        }
        if options.opaque_fields == OpaqueFieldPolicy::Block
            && (doc.resource.is_none() || has_unknown_fields(&tree, doc.capability.as_ref().map_or(&[], |c| c.fields)))
        {
            findings.push(Finding::error(FindingCode::OpaqueOutputDenied, Phase::Generation).for_resource(doc.id));
        }
        let mut protected_paths = Vec::new();
        if let Some(resource) = &projection.resource {
            resource.collect_protected_paths(&mut protected_paths);
        }
        let codec_protected = protected_paths
            .iter()
            .any(|path| tree.get_path(path).is_some_and(|node| node.value != TreeValue::Null));
        if options.protected_output == ProtectedOutput::Deny
            && (codec_protected
                || protected(&tree)
                || doc.original_identity.scope.namespaced().is_none()
                || matches!(
                    doc.original_identity.scope,
                    crate::model::ResourceScope::CrdResolved { .. }
                ))
        {
            findings.push(Finding::error(FindingCode::ProtectedOutputDenied, Phase::Generation).for_resource(doc.id));
        }
        if contains_tags(&tree) {
            findings.push(Finding::error(FindingCode::UnsupportedScalar, Phase::Generation).for_resource(doc.id));
        }
        trees.insert(doc.id, tree);
    }
    let wrappers = prepare_wrappers(resources, options, &mut findings);
    if has_errors(&findings) {
        return Err(findings);
    }
    let mut ordered: Vec<_> = resources.documents.iter().collect();
    ordered.sort_by_key(|doc| {
        trees
            .get(&doc.id)
            .and_then(|tree| crate::model::identity(tree, doc.original_identity.scope).ok())
            .map(|identity| (identity.gvk, identity.scope, identity.namespace, identity.name, doc.id))
    });
    let mut roots = Vec::new();
    if options.collections == CollectionOutput::PreserveWrappers {
        for list in resources.lists.iter().filter(|list| list.collection.is_none()) {
            roots.push(rewrap(resources, list.id, &trees, &wrappers).map_err(|e| vec![e])?);
        }
        roots.extend(
            ordered
                .iter()
                .filter(|doc| doc.collection.is_none())
                .filter_map(|doc| trees.get(&doc.id).cloned()),
        );
    } else {
        roots.extend(ordered.iter().filter_map(|doc| trees.get(&doc.id).cloned()));
    }
    let mut bytes = String::new();
    match format {
        OutputFormat::Json => {
            let root = match options.json_shape {
                JsonShape::SingleResource => {
                    if roots.len() != 1 {
                        return Err(vec![Finding::error(FindingCode::MalformedDocument, Phase::Generation)]);
                    }
                    roots.remove(0)
                }
                JsonShape::KubernetesList => list_tree(roots),
            };
            json(&root, &mut bytes).map_err(|e| vec![e])?;
            bytes.push('\n');
        }
        OutputFormat::Yaml => {
            for root in roots {
                bytes.push_str("---\n");
                json(&root, &mut bytes).map_err(|e| vec![e])?;
                bytes.push('\n');
            }
        }
    }
    Ok(GeneratedArtifact {
        format,
        bytes: Arc::from(bytes.into_bytes()),
        findings,
    })
}
fn prepare_wrappers(
    resources: &ResourceSet,
    options: &GenerationOptions,
    findings: &mut Vec<Finding>,
) -> BTreeMap<crate::model::ListId, TreeNode> {
    let mut wrappers = BTreeMap::new();
    for list in &resources.lists {
        let mut tree = list.original.clone();
        let unknown = wrapper_unknown_paths(&tree);
        for path in &unknown {
            findings.push(wrapper_finding(
                list,
                FindingCode::UnadmittedField,
                Phase::Validation,
                path.clone(),
                false,
            ));
        }
        if options.opaque_fields == OpaqueFieldPolicy::Block && !unknown.is_empty() {
            findings.push(wrapper_finding(
                list,
                FindingCode::OpaqueOutputDenied,
                Phase::Generation,
                unknown[0].clone(),
                true,
            ));
        }
        if options.protected_output == ProtectedOutput::Deny
            && (!unknown.is_empty()
                || tree
                    .get("metadata")
                    .and_then(|metadata| metadata.get("continue"))
                    .is_some_and(|node| node.value != TreeValue::Null))
        {
            findings.push(wrapper_finding(
                list,
                FindingCode::ProtectedOutputDenied,
                Phase::Generation,
                FieldPath::default(),
                true,
            ));
        }
        if contains_tags(&tree) {
            findings.push(wrapper_finding(
                list,
                FindingCode::UnsupportedScalar,
                Phase::Generation,
                FieldPath::default(),
                true,
            ));
        }
        if options.intent == OutputIntent::AuthoredIntent {
            let begin = findings.len();
            strip_wrapper_observed(&mut tree, findings);
            for finding in &mut findings[begin..] {
                finding.wrapper = Some(WrapperSubject {
                    source: list.source,
                    list: list.id,
                });
                finding.source = finding
                    .path
                    .as_ref()
                    .and_then(|path| list.original.get_path(path))
                    .and_then(|node| node.start);
            }
        }
        if options.collections == CollectionOutput::Flatten {
            if let Some(entries) = tree.as_mapping() {
                for (key, _) in entries {
                    if !matches!(key.as_str(), "apiVersion" | "kind" | "items") {
                        findings.push(wrapper_finding(
                            list,
                            FindingCode::CollectionFieldRemoved,
                            Phase::Generation,
                            FieldPath(vec![key.clone()]),
                            false,
                        ));
                    }
                }
            }
        }
        wrappers.insert(list.id, tree);
    }
    wrappers
}
fn list_tree(items: Vec<TreeNode>) -> TreeNode {
    TreeNode::mapping(vec![
        ("apiVersion".into(), TreeNode::string("v1")),
        ("kind".into(), TreeNode::string("List")),
        ("items".into(), TreeNode::new(TreeValue::Sequence(items))),
    ])
}
fn rewrap(
    resources: &ResourceSet,
    id: crate::model::ListId,
    trees: &BTreeMap<ResourceId, TreeNode>,
    wrappers: &BTreeMap<crate::model::ListId, TreeNode>,
) -> Result<TreeNode, Finding> {
    let list = resources.lists.iter().find(|list| list.id == id).ok_or_else(conflict)?;
    let result = (|| {
        let mut wrapper = wrappers.get(&id).cloned().ok_or_else(conflict)?;
        let Some(items) = wrapper.get("items").and_then(TreeNode::as_sequence) else {
            return Err(conflict());
        };
        let mut current = Vec::new();
        for index in 0..items.len() {
            if let Some(nested) = resources.lists.iter().find(|l| {
                l.collection
                    .as_ref()
                    .is_some_and(|path| path.items.last() == Some(&(id, index)))
            }) {
                current.push(rewrap(resources, nested.id, trees, wrappers)?);
            } else if let Some(doc) = resources.documents.iter().find(|d| {
                d.collection
                    .as_ref()
                    .is_some_and(|path| path.items.last() == Some(&(id, index)))
            }) {
                current.push(trees.get(&doc.id).cloned().ok_or_else(conflict)?);
            } else {
                return Err(conflict());
            }
        }
        set_child(&mut wrapper, "items", Some(TreeNode::new(TreeValue::Sequence(current))))?;
        Ok(wrapper)
    })();
    result.map_err(|mut finding: Finding| {
        if finding.wrapper.is_none() {
            finding = finding.for_wrapper(WrapperSubject {
                source: list.source,
                list: id,
            });
        }
        if finding.source.is_none() {
            finding.source = list.original.start;
        }
        finding
    })
}
fn strip_wrapper_observed(tree: &mut TreeNode, findings: &mut Vec<Finding>) {
    strip_observation_paths(tree, None, &crate::source::list_observation_paths(), findings);
}
fn wrapper_unknown_paths(tree: &TreeNode) -> Vec<FieldPath> {
    let mut paths = Vec::new();
    if let Some(entries) = tree.as_mapping() {
        for (key, value) in entries {
            let path = FieldPath(vec![key.clone()]);
            if key == "metadata" {
                if let Some(metadata) = value.as_mapping() {
                    for (name, _) in metadata {
                        if !matches!(
                            name.as_str(),
                            "resourceVersion" | "selfLink" | "continue" | "remainingItemCount"
                        ) {
                            paths.push(path.child(name));
                        }
                    }
                } else {
                    paths.push(path);
                }
            } else if !matches!(key.as_str(), "apiVersion" | "kind" | "items") {
                paths.push(path);
            }
        }
    }
    paths
}
fn wrapper_finding(
    list: &crate::model::ListDocument,
    code: FindingCode,
    phase: Phase,
    path: FieldPath,
    blocking: bool,
) -> Finding {
    let mut finding = if blocking {
        Finding::error(code, phase)
    } else {
        Finding::warning(code, phase)
    };
    finding.source = list
        .original
        .get_path(&path)
        .and_then(|node| node.start)
        .or(list.original.start);
    finding.path = Some(path);
    finding.for_wrapper(WrapperSubject {
        source: list.source,
        list: list.id,
    })
}
fn protected(tree: &TreeNode) -> bool {
    tree.get("kind").and_then(TreeNode::as_str) == Some("Secret")
        && ["data", "stringData"]
            .iter()
            .any(|key| tree.get(key).is_some_and(|n| n.value != TreeValue::Null))
}
fn contains_tags(tree: &TreeNode) -> bool {
    match &tree.value {
        TreeValue::Tagged(..) => true,
        TreeValue::Mapping(entries) => entries.iter().any(|(_, n)| contains_tags(n)),
        TreeValue::Sequence(items) => items.iter().any(contains_tags),
        _ => false,
    }
}
fn strip_observation_paths(
    tree: &mut TreeNode,
    id: Option<ResourceId>,
    observations: &[crate::source::ObservationPath],
    findings: &mut Vec<Finding>,
) {
    let mut paths = observations
        .iter()
        .filter(|observation| {
            matches!(
                observation.role,
                crate::source::ObservationRole::ServerOwned | crate::source::ObservationRole::SubresourceOnly
            )
        })
        .map(|observation| observation.path.clone())
        .collect::<Vec<_>>();
    paths.sort_by(|left, right| left.0.len().cmp(&right.0.len()).then(left.cmp(right)));
    let mut removed: Vec<FieldPath> = Vec::new();
    for path in paths {
        if removed.iter().any(|parent| path.0.starts_with(&parent.0)) || tree.get_path(&path).is_none() {
            continue;
        }
        match apply_edit(tree, &FieldEdit::Remove { path: path.clone() }) {
            Ok(()) => {
                // Retain source validation findings, but stripped opaque observations no longer block output.
                for finding in findings.iter_mut().filter(|finding| {
                    finding.resource == id
                        && finding.code == FindingCode::UnadmittedField
                        && finding
                            .path
                            .as_ref()
                            .is_some_and(|finding| finding.0.starts_with(&path.0))
                }) {
                    finding.severity = Severity::Warning;
                }
                let mut finding =
                    Finding::warning(FindingCode::ObservedFieldRemoved, Phase::Generation).at_path(path.clone());
                finding.resource = id;
                finding.severity = Severity::Information;
                findings.push(finding);
                removed.push(path);
            }
            Err(finding) => findings.push(finding),
        }
    }
}
fn has_unknown_fields(tree: &TreeNode, fields: &[FieldCapability]) -> bool {
    fn visit(node: &TreeNode, path: &FieldPath, fields: &[FieldCapability]) -> bool {
        if path.0.len() == 1 && matches!(path.0[0].as_str(), "apiVersion" | "kind") {
            return false;
        }
        let admitted = fields.iter().any(|field| {
            FieldPath::parse(field.path).is_ok_and(|p| {
                p.0.len() == path.0.len()
                    && p.0.iter().zip(&path.0).all(|(a, b)| a == "*" || a == b)
                    && field.admission == FieldAdmission::Typed
            })
        });
        match &node.value {
            TreeValue::Mapping(entries) => {
                (entries.is_empty() && !path.0.is_empty() && !admitted)
                    || entries.iter().any(|(key, n)| visit(n, &path.child(key), fields))
            }
            TreeValue::Sequence(items) => {
                (items.is_empty() && !admitted)
                    || items
                        .iter()
                        .enumerate()
                        .any(|(index, n)| visit(n, &path.child(index.to_string()), fields))
            }
            _ => !admitted,
        }
    }
    visit(tree, &FieldPath::default(), fields)
}
fn conflict() -> Finding {
    Finding::error(FindingCode::MergeConflict, Phase::Generation)
}
fn strategy(path: &FieldPath, fields: &[FieldCapability]) -> MergeStrategy {
    fields
        .iter()
        .find(|f| {
            FieldPath::parse(f.path)
                .is_ok_and(|p| p.0.len() == path.0.len() && p.0.iter().zip(&path.0).all(|(a, b)| a == "*" || a == b))
        })
        .map_or(MergeStrategy::AtomicList, |f| f.merge)
}
fn unknown_descendants(raw: &TreeNode, known: &TreeNode) -> bool {
    match (&raw.value, &known.value) {
        (TreeValue::Mapping(raw), TreeValue::Mapping(known)) => raw.iter().any(|(key, value)| {
            known
                .iter()
                .find(|(k, _)| k == key)
                .is_none_or(|(_, known)| unknown_descendants(value, known))
        }),
        (TreeValue::Sequence(raw), TreeValue::Sequence(known)) => {
            raw.len() != known.len() || raw.iter().zip(known).any(|(r, k)| unknown_descendants(r, k))
        }
        _ => false,
    }
}
fn merge_delta_inner(
    raw: &TreeNode,
    before: &TreeNode,
    after: &TreeNode,
    path: &FieldPath,
    fields: &[FieldCapability],
    resolutions: &[FieldEdit],
    context: MergeContext<'_>,
) -> Result<TreeNode, Finding> {
    let gvk = context.gvk;
    let target = context.target;
    if before.semantic_eq(after)
        || resolutions.iter().any(|edit| {
            let edited = match edit {
                FieldEdit::Set { path, .. } | FieldEdit::Remove { path } => path,
            };
            edited.0.len() <= path.0.len() && path.0.starts_with(&edited.0)
        })
    {
        return Ok(raw.clone());
    }
    match (&before.value, &after.value, &raw.value) {
        (TreeValue::Mapping(before), TreeValue::Mapping(after), TreeValue::Mapping(_)) => {
            let mut out = raw.clone();
            for (key, old) in before {
                if let Some((_, new)) = after.iter().find(|(k, _)| k == key) {
                    let original = raw.get(key).unwrap_or(old);
                    set_child(
                        &mut out,
                        key,
                        Some(merge_delta_inner(
                            original,
                            old,
                            new,
                            &path.child(key),
                            fields,
                            resolutions,
                            context,
                        )?),
                    )?;
                } else {
                    let child = path.child(key);
                    let explicit = resolutions.iter().any(|edit| {
                        let edit = match edit {
                            FieldEdit::Set { path, .. } | FieldEdit::Remove { path } => path,
                        };
                        child.0.starts_with(&edit.0)
                    });
                    if raw.get(key).is_some_and(|raw| unknown_descendants(raw, old)) && !explicit {
                        return Err(conflict().at_path(child));
                    }
                    set_child(&mut out, key, None)?;
                }
            }
            for (key, new) in after {
                if !before.iter().any(|(k, _)| k == key) {
                    set_child(&mut out, key, Some(new.clone()))?;
                }
            }
            Ok(out)
        }
        (TreeValue::Sequence(before_items), TreeValue::Sequence(after_items), TreeValue::Sequence(raw_items)) => {
            if let MergeStrategy::MapList { keys } = strategy(path, fields) {
                if keys.is_empty() {
                    return Err(conflict().at_path(path.clone()));
                }
                let old = keyed(before_items, keys, path, gvk, target)?;
                let raw = keyed(raw_items, keys, path, gvk, target)?;
                let new = keyed(after_items, keys, path, gvk, target)?;
                for (key, previous) in &old {
                    if !new.contains_key(key)
                        && raw
                            .get(key)
                            .is_some_and(|original| unknown_descendants(original, previous))
                    {
                        return Err(conflict().at_path(path.clone()));
                    }
                }
                let mut out = Vec::new();
                for (index, node) in after_items.iter().enumerate() {
                    let key = list_key(node, keys, path, gvk, target)?;
                    if let (Some(before), Some(original)) = (old.get(&key), raw.get(&key)) {
                        out.push(merge_delta_inner(
                            original,
                            before,
                            node,
                            &path.child(index.to_string()),
                            fields,
                            resolutions,
                            context,
                        )?);
                    } else {
                        out.push(node.clone());
                    }
                }
                // Validation of duplicate keys above is independent of reordering/removal.
                let _ = keyed(&out, keys, path, gvk, target)?;
                Ok(TreeNode {
                    value: TreeValue::Sequence(out),
                    start: raw_items.first().and_then(|n| n.start),
                })
            } else if unknown_descendants(raw, before) {
                Err(conflict().at_path(path.clone()))
            } else {
                Ok(after.clone())
            }
        }
        _ if unknown_descendants(raw, before) => Err(conflict().at_path(path.clone())),
        _ => Ok(after.clone()),
    }
}
fn list_key(
    node: &TreeNode,
    keys: &[&str],
    path: &FieldPath,
    gvk: Option<&crate::model::GroupVersionKind>,
    target: Option<&TargetProfile>,
) -> Result<Vec<String>, Finding> {
    let tcp = port_tcp_rule(path, gvk, target);
    if tcp {
        let port_key = if keys == ["port", "protocol"] {
            "port"
        } else if keys == ["containerPort", "protocol"] {
            "containerPort"
        } else {
            return Err(conflict().at_path(path.clone()));
        };
        let valid_port = node.get(port_key).is_some_and(|node| matches!(&node.value, TreeValue::Number(number) if number.parse::<i32>().is_ok_and(|port| (1..=65535).contains(&port))));
        let valid_protocol = node.get("protocol").is_none_or(|node| {
            node.as_str()
                .is_some_and(|protocol| matches!(protocol, "TCP" | "UDP" | "SCTP"))
        });
        if !valid_port || !valid_protocol {
            return Err(conflict().at_path(path.clone()));
        }
    }
    keys.iter()
        .map(|key| {
            let Some(node) = node.get(key) else {
                return if tcp && *key == "protocol" {
                    Ok(String::from("\"TCP\""))
                } else {
                    Err(conflict().at_path(path.clone()))
                };
            };
            if matches!(
                node.value,
                TreeValue::Mapping(_) | TreeValue::Sequence(_) | TreeValue::Null | TreeValue::Tagged(..)
            ) {
                return Err(conflict());
            }
            let mut text = String::new();
            json(node, &mut text)?;
            Ok(text)
        })
        .collect()
}
fn keyed<'a>(
    items: &'a [TreeNode],
    keys: &[&str],
    path: &FieldPath,
    gvk: Option<&crate::model::GroupVersionKind>,
    target: Option<&TargetProfile>,
) -> Result<BTreeMap<Vec<String>, &'a TreeNode>, Finding> {
    let mut out = BTreeMap::new();
    for node in items {
        if out.insert(list_key(node, keys, path, gvk, target)?, node).is_some() {
            return Err(conflict().at_path(path.clone()));
        }
    }
    Ok(out)
}
fn set_child(node: &mut TreeNode, key: &str, value: Option<TreeNode>) -> Result<(), Finding> {
    let TreeValue::Mapping(entries) = &mut node.value else {
        return Err(conflict());
    };
    if let Some(index) = entries.iter().position(|(k, _)| k == key) {
        if let Some(value) = value {
            entries[index].1 = value;
        } else {
            entries.remove(index);
        }
    } else if let Some(value) = value {
        entries.push((key.to_owned(), value));
    }
    Ok(())
}
pub(crate) fn apply_edit(tree: &mut TreeNode, edit: &FieldEdit) -> Result<(), Finding> {
    let (path, value) = match edit {
        FieldEdit::Set { path, value } => (path, Some(value.clone())),
        FieldEdit::Remove { path } => (path, None),
    };
    let Some((last, parents)) = path.0.split_last() else {
        return Err(conflict().at_path(path.clone()));
    };
    let mut node = tree;
    for parent in parents {
        match &mut node.value {
            TreeValue::Mapping(entries) => {
                let Some(index) = entries.iter().position(|(key, _)| key == parent) else {
                    return Err(conflict().at_path(path.clone()));
                };
                node = &mut entries[index].1;
            }
            TreeValue::Sequence(items) => {
                let index: usize = parent.parse().map_err(|_| conflict())?;
                node = items.get_mut(index).ok_or_else(conflict)?;
            }
            _ => return Err(conflict().at_path(path.clone())),
        }
    }
    match &mut node.value {
        TreeValue::Sequence(items) => {
            let index: usize = last.parse().map_err(|_| conflict())?;
            if index >= items.len() {
                return Err(conflict());
            }
            if let Some(value) = value {
                items[index] = value;
            } else {
                items.remove(index);
            }
            Ok(())
        }
        _ => set_child(node, last, value),
    }
}
pub(crate) fn json(node: &TreeNode, out: &mut String) -> Result<(), Finding> {
    match &node.value {
        TreeValue::Null => out.push_str("null"),
        TreeValue::Bool(value) => out.push_str(if *value { "true" } else { "false" }),
        TreeValue::Number(value) => out.push_str(value),
        TreeValue::String(value) => out.push_str(&serde_json::to_string(value).map_err(|_| conflict())?),
        TreeValue::Sequence(items) => {
            out.push('[');
            for (index, item) in items.iter().enumerate() {
                if index > 0 {
                    out.push(',');
                }
                json(item, out)?;
            }
            out.push(']');
        }
        TreeValue::Mapping(entries) => {
            out.push('{');
            let mut entries: Vec<_> = entries.iter().collect();
            entries.sort_by(|(a, _), (b, _)| a.cmp(b));
            let mut seen = BTreeSet::new();
            for (index, (key, value)) in entries.into_iter().enumerate() {
                if !seen.insert(key) {
                    return Err(conflict());
                }
                if index > 0 {
                    out.push(',');
                }
                out.push_str(&serde_json::to_string(key).map_err(|_| conflict())?);
                out.push(':');
                json(value, out)?;
            }
            out.push('}');
        }
        TreeValue::Tagged(..) => return Err(Finding::error(FindingCode::UnsupportedScalar, Phase::Generation)),
    }
    Ok(())
}

/// Validate all declared map-list identities even when no semantic edit occurred.
pub(crate) fn merge_native_delta(
    raw: &TreeNode,
    before: &TreeNode,
    after: &TreeNode,
    path: &FieldPath,
    fields: &[FieldCapability],
    resolutions: &[FieldEdit],
    context: MergeContext<'_>,
) -> Result<TreeNode, Finding> {
    let merged = merge_delta_inner(raw, before, after, path, fields, resolutions, context)?;
    // Explicit caller repair is applied to the checked view, never to immutable originals.
    let mut checked = merged.clone();
    for edit in resolutions {
        let (edited, value) = match edit {
            FieldEdit::Set { path, value } => (path, Some(value)),
            FieldEdit::Remove { path } => (path, None),
        };
        if edited.0.starts_with(&path.0) {
            let relative = FieldPath(edited.0[path.0.len()..].to_vec());
            if relative.0.is_empty() {
                checked = value.cloned().unwrap_or_else(|| TreeNode::new(TreeValue::Null));
            } else {
                let relative = match value {
                    Some(value) => FieldEdit::Set {
                        path: relative,
                        value: value.clone(),
                    },
                    None => FieldEdit::Remove { path: relative },
                };
                apply_edit(&mut checked, &relative)?;
            }
        } else if path.0.starts_with(&edited.0) {
            checked = TreeNode::new(TreeValue::Null);
        }
    }
    check_supplied_list_duplicates(&checked, path, fields, context.gvk, context.target)?;
    Ok(merged)
}
#[cfg(test)]
pub(crate) fn merge_delta(
    raw: &TreeNode,
    before: &TreeNode,
    after: &TreeNode,
    path: &FieldPath,
    fields: &[FieldCapability],
    resolutions: &[FieldEdit],
) -> Result<TreeNode, Finding> {
    merge_native_delta(
        raw,
        before,
        after,
        path,
        fields,
        resolutions,
        MergeContext {
            gvk: None,
            target: None,
        },
    )
}
fn check_supplied_list_duplicates(
    tree: &TreeNode,
    path: &FieldPath,
    fields: &[FieldCapability],
    gvk: Option<&crate::model::GroupVersionKind>,
    target: Option<&TargetProfile>,
) -> Result<(), Finding> {
    match &tree.value {
        TreeValue::Sequence(items) => {
            if let MergeStrategy::MapList { keys } = strategy(path, fields) {
                let mut seen = BTreeSet::new();
                for item in items {
                    // Preserve malformed unchanged source values for exact native validation.
                    // Every valid key is still scanned, including those after malformed siblings.
                    if let Ok(key) = list_key(item, keys, path, gvk, target) {
                        if !seen.insert(key) {
                            return Err(conflict().at_path(path.clone()));
                        }
                    }
                }
            }
            for (index, item) in items.iter().enumerate() {
                check_supplied_list_duplicates(item, &path.child(index.to_string()), fields, gvk, target)?;
            }
        }
        TreeValue::Mapping(entries) => {
            for (key, node) in entries {
                check_supplied_list_duplicates(node, &path.child(key), fields, gvk, target)?;
            }
        }
        _ => {}
    }
    Ok(())
}
fn port_tcp_rule(
    path: &FieldPath,
    gvk: Option<&crate::model::GroupVersionKind>,
    target: Option<&TargetProfile>,
) -> bool {
    let Some(gvk) = gvk else {
        return false;
    };
    if target.is_some_and(|target| {
        declaration(gvk)
            .is_none_or(|declaration| !(declaration.first..=declaration.last).contains(&target.kubernetes.minor()))
    }) {
        return false;
    }
    let prefix = match (gvk.group.as_deref(), gvk.version.as_str(), gvk.kind.as_str()) {
        (None, "v1", "Service") => return path.0 == ["spec", "ports"],
        (None, "v1", "Pod") => "/spec",
        (None, "v1", "ReplicationController")
        | (Some("apps"), "v1", "Deployment" | "StatefulSet" | "DaemonSet" | "ReplicaSet")
        | (Some("batch"), "v1", "Job") => "/spec/template/spec",
        (Some("batch"), "v1" | "v1beta1", "CronJob") => "/spec/jobTemplate/spec/template/spec",
        _ => return false,
    };
    let Ok(prefix) = FieldPath::parse(prefix) else {
        return false;
    };
    path.0.len() == prefix.0.len() + 3
        && path.0.starts_with(&prefix.0)
        && matches!(path.0[prefix.0.len()].as_str(), "containers" | "initContainers")
        && (path.0[prefix.0.len() + 1] == "*" || path.0[prefix.0.len() + 1].parse::<usize>().is_ok())
        && path.0[prefix.0.len() + 2] == "ports"
}

#[derive(Clone, Copy)]
pub(crate) struct MergeContext<'a> {
    pub(crate) gvk: Option<&'a crate::model::GroupVersionKind>,
    pub(crate) target: Option<&'a TargetProfile>,
}
