//! Value-dependent native admission predicates retain exact target/gate choices.
use crate::{
    capability::{FeatureGateId, FeatureGateState, TargetProfile},
    diagnostic::{FieldPath, Finding, FindingCode, Phase},
    registry::FindingSink,
    syntax::TreeNode,
};
type Rule = (&'static str, FeatureGateId, u8, Option<&'static [&'static str]>);
const RULES_0: &[Rule] = &[
    (
        "/spec/containers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/containers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/containers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/containers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    (
        "/spec/initContainers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/initContainers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/initContainers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/initContainers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    ("/spec/overhead", FeatureGateId::PodOverhead, 24, None),
    ("/spec/preemptionPolicy", FeatureGateId::NonPreemptingPriority, 24, None),
    ("/spec/runtimeClassName", FeatureGateId::RuntimeClass, 20, None),
    (
        "/spec/securityContext/fsGroupChangePolicy",
        FeatureGateId::ConfigurableFSGroupPolicy,
        23,
        None,
    ),
    ("/spec/setHostnameAsFQDN", FeatureGateId::SetHostnameAsFQDN, 22, None),
    ("/spec/volumes/*/csi", FeatureGateId::CSIInlineVolume, 25, None),
    (
        "/spec/volumes/*/ephemeral",
        FeatureGateId::GenericEphemeralVolume,
        23,
        None,
    ),
];
const RULES_1: &[Rule] = &[
    (
        "/spec/template/spec/containers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/template/spec/containers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/template/spec/containers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/template/spec/containers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/template/spec/initContainers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    ("/spec/template/spec/overhead", FeatureGateId::PodOverhead, 24, None),
    (
        "/spec/template/spec/preemptionPolicy",
        FeatureGateId::NonPreemptingPriority,
        24,
        None,
    ),
    (
        "/spec/template/spec/runtimeClassName",
        FeatureGateId::RuntimeClass,
        20,
        None,
    ),
    (
        "/spec/template/spec/securityContext/fsGroupChangePolicy",
        FeatureGateId::ConfigurableFSGroupPolicy,
        23,
        None,
    ),
    (
        "/spec/template/spec/setHostnameAsFQDN",
        FeatureGateId::SetHostnameAsFQDN,
        22,
        None,
    ),
    (
        "/spec/template/spec/volumes/*/csi",
        FeatureGateId::CSIInlineVolume,
        25,
        None,
    ),
    (
        "/spec/template/spec/volumes/*/ephemeral",
        FeatureGateId::GenericEphemeralVolume,
        23,
        None,
    ),
];
const RULES_2: &[Rule] = &[
    (
        "/spec/minReadySeconds",
        FeatureGateId::StatefulSetMinReadySeconds,
        25,
        None,
    ),
    ("/spec/ordinals", FeatureGateId::StatefulSetStartOrdinal, 31, None),
    (
        "/spec/persistentVolumeClaimRetentionPolicy",
        FeatureGateId::StatefulSetAutoDeletePVC,
        20,
        None,
    ),
    (
        "/spec/template/spec/containers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/template/spec/containers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/template/spec/containers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/template/spec/containers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/template/spec/initContainers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    ("/spec/template/spec/overhead", FeatureGateId::PodOverhead, 24, None),
    (
        "/spec/template/spec/preemptionPolicy",
        FeatureGateId::NonPreemptingPriority,
        24,
        None,
    ),
    (
        "/spec/template/spec/runtimeClassName",
        FeatureGateId::RuntimeClass,
        20,
        None,
    ),
    (
        "/spec/template/spec/securityContext/fsGroupChangePolicy",
        FeatureGateId::ConfigurableFSGroupPolicy,
        23,
        None,
    ),
    (
        "/spec/template/spec/setHostnameAsFQDN",
        FeatureGateId::SetHostnameAsFQDN,
        22,
        None,
    ),
    (
        "/spec/template/spec/volumes/*/csi",
        FeatureGateId::CSIInlineVolume,
        25,
        None,
    ),
    (
        "/spec/template/spec/volumes/*/ephemeral",
        FeatureGateId::GenericEphemeralVolume,
        23,
        None,
    ),
];
const RULES_3: &[Rule] = &[
    (
        "/spec/template/spec/containers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/template/spec/containers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/template/spec/containers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/template/spec/containers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/template/spec/initContainers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    ("/spec/template/spec/overhead", FeatureGateId::PodOverhead, 24, None),
    (
        "/spec/template/spec/preemptionPolicy",
        FeatureGateId::NonPreemptingPriority,
        24,
        None,
    ),
    (
        "/spec/template/spec/runtimeClassName",
        FeatureGateId::RuntimeClass,
        20,
        None,
    ),
    (
        "/spec/template/spec/securityContext/fsGroupChangePolicy",
        FeatureGateId::ConfigurableFSGroupPolicy,
        23,
        None,
    ),
    (
        "/spec/template/spec/setHostnameAsFQDN",
        FeatureGateId::SetHostnameAsFQDN,
        22,
        None,
    ),
    (
        "/spec/template/spec/volumes/*/csi",
        FeatureGateId::CSIInlineVolume,
        25,
        None,
    ),
    (
        "/spec/template/spec/volumes/*/ephemeral",
        FeatureGateId::GenericEphemeralVolume,
        23,
        None,
    ),
    (
        "/spec/updateStrategy/rollingUpdate/maxSurge",
        FeatureGateId::DaemonSetUpdateSurge,
        25,
        None,
    ),
];
const RULES_4: &[Rule] = &[
    (
        "/spec/template/spec/containers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/template/spec/containers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/template/spec/containers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/template/spec/containers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/template/spec/initContainers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    ("/spec/template/spec/overhead", FeatureGateId::PodOverhead, 24, None),
    (
        "/spec/template/spec/preemptionPolicy",
        FeatureGateId::NonPreemptingPriority,
        24,
        None,
    ),
    (
        "/spec/template/spec/runtimeClassName",
        FeatureGateId::RuntimeClass,
        20,
        None,
    ),
    (
        "/spec/template/spec/securityContext/fsGroupChangePolicy",
        FeatureGateId::ConfigurableFSGroupPolicy,
        23,
        None,
    ),
    (
        "/spec/template/spec/setHostnameAsFQDN",
        FeatureGateId::SetHostnameAsFQDN,
        22,
        None,
    ),
    (
        "/spec/template/spec/volumes/*/csi",
        FeatureGateId::CSIInlineVolume,
        25,
        None,
    ),
    (
        "/spec/template/spec/volumes/*/ephemeral",
        FeatureGateId::GenericEphemeralVolume,
        23,
        None,
    ),
];
const RULES_5: &[Rule] = &[
    (
        "/spec/template/spec/containers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/template/spec/containers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/template/spec/containers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/template/spec/containers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/template/spec/initContainers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    ("/spec/template/spec/overhead", FeatureGateId::PodOverhead, 24, None),
    (
        "/spec/template/spec/preemptionPolicy",
        FeatureGateId::NonPreemptingPriority,
        24,
        None,
    ),
    (
        "/spec/template/spec/runtimeClassName",
        FeatureGateId::RuntimeClass,
        20,
        None,
    ),
    (
        "/spec/template/spec/securityContext/fsGroupChangePolicy",
        FeatureGateId::ConfigurableFSGroupPolicy,
        23,
        None,
    ),
    (
        "/spec/template/spec/setHostnameAsFQDN",
        FeatureGateId::SetHostnameAsFQDN,
        22,
        None,
    ),
    (
        "/spec/template/spec/volumes/*/csi",
        FeatureGateId::CSIInlineVolume,
        25,
        None,
    ),
    (
        "/spec/template/spec/volumes/*/ephemeral",
        FeatureGateId::GenericEphemeralVolume,
        23,
        None,
    ),
];
const RULES_6: &[Rule] = &[
    (
        "/spec/backoffLimitPerIndex",
        FeatureGateId::JobBackoffLimitPerIndex,
        33,
        None,
    ),
    (
        "/spec/completionMode",
        FeatureGateId::IndexedJob,
        24,
        Some(&["Indexed"]),
    ),
    (
        "/spec/maxFailedIndexes",
        FeatureGateId::JobBackoffLimitPerIndex,
        33,
        None,
    ),
    ("/spec/podFailurePolicy", FeatureGateId::JobPodFailurePolicy, 31, None),
    ("/spec/successPolicy", FeatureGateId::JobSuccessPolicy, 33, None),
    ("/spec/suspend", FeatureGateId::SuspendJob, 24, None),
    (
        "/spec/template/spec/containers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/template/spec/containers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/template/spec/containers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/template/spec/containers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/template/spec/initContainers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/template/spec/initContainers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    ("/spec/template/spec/overhead", FeatureGateId::PodOverhead, 24, None),
    (
        "/spec/template/spec/preemptionPolicy",
        FeatureGateId::NonPreemptingPriority,
        24,
        None,
    ),
    (
        "/spec/template/spec/runtimeClassName",
        FeatureGateId::RuntimeClass,
        20,
        None,
    ),
    (
        "/spec/template/spec/securityContext/fsGroupChangePolicy",
        FeatureGateId::ConfigurableFSGroupPolicy,
        23,
        None,
    ),
    (
        "/spec/template/spec/setHostnameAsFQDN",
        FeatureGateId::SetHostnameAsFQDN,
        22,
        None,
    ),
    (
        "/spec/template/spec/volumes/*/csi",
        FeatureGateId::CSIInlineVolume,
        25,
        None,
    ),
    (
        "/spec/template/spec/volumes/*/ephemeral",
        FeatureGateId::GenericEphemeralVolume,
        23,
        None,
    ),
    (
        "/spec/ttlSecondsAfterFinished",
        FeatureGateId::TTLAfterFinished,
        23,
        None,
    ),
];
const RULES_7: &[Rule] = &[
    (
        "/spec/jobTemplate/spec/backoffLimitPerIndex",
        FeatureGateId::JobBackoffLimitPerIndex,
        33,
        None,
    ),
    (
        "/spec/jobTemplate/spec/completionMode",
        FeatureGateId::IndexedJob,
        24,
        Some(&["Indexed"]),
    ),
    (
        "/spec/jobTemplate/spec/maxFailedIndexes",
        FeatureGateId::JobBackoffLimitPerIndex,
        33,
        None,
    ),
    (
        "/spec/jobTemplate/spec/podFailurePolicy",
        FeatureGateId::JobPodFailurePolicy,
        31,
        None,
    ),
    (
        "/spec/jobTemplate/spec/successPolicy",
        FeatureGateId::JobSuccessPolicy,
        33,
        None,
    ),
    ("/spec/jobTemplate/spec/suspend", FeatureGateId::SuspendJob, 24, None),
    (
        "/spec/jobTemplate/spec/template/spec/containers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/containers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/containers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/jobTemplate/spec/template/spec/containers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/initContainers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/initContainers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/initContainers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/jobTemplate/spec/template/spec/initContainers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/overhead",
        FeatureGateId::PodOverhead,
        24,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/preemptionPolicy",
        FeatureGateId::NonPreemptingPriority,
        24,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/runtimeClassName",
        FeatureGateId::RuntimeClass,
        20,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/securityContext/fsGroupChangePolicy",
        FeatureGateId::ConfigurableFSGroupPolicy,
        23,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/setHostnameAsFQDN",
        FeatureGateId::SetHostnameAsFQDN,
        22,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/volumes/*/csi",
        FeatureGateId::CSIInlineVolume,
        25,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/volumes/*/ephemeral",
        FeatureGateId::GenericEphemeralVolume,
        23,
        None,
    ),
    (
        "/spec/jobTemplate/spec/ttlSecondsAfterFinished",
        FeatureGateId::TTLAfterFinished,
        23,
        None,
    ),
    ("/spec/timeZone", FeatureGateId::CronJobTimeZone, 27, None),
];
const RULES_8: &[Rule] = &[
    (
        "/spec/jobTemplate/spec/backoffLimitPerIndex",
        FeatureGateId::JobBackoffLimitPerIndex,
        33,
        None,
    ),
    (
        "/spec/jobTemplate/spec/completionMode",
        FeatureGateId::IndexedJob,
        24,
        Some(&["Indexed"]),
    ),
    (
        "/spec/jobTemplate/spec/maxFailedIndexes",
        FeatureGateId::JobBackoffLimitPerIndex,
        33,
        None,
    ),
    (
        "/spec/jobTemplate/spec/podFailurePolicy",
        FeatureGateId::JobPodFailurePolicy,
        31,
        None,
    ),
    (
        "/spec/jobTemplate/spec/successPolicy",
        FeatureGateId::JobSuccessPolicy,
        33,
        None,
    ),
    ("/spec/jobTemplate/spec/suspend", FeatureGateId::SuspendJob, 24, None),
    (
        "/spec/jobTemplate/spec/template/spec/containers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/containers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/containers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/jobTemplate/spec/template/spec/containers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/initContainers/*/resizePolicy",
        FeatureGateId::InPlacePodVerticalScaling,
        35,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/initContainers/*/restartPolicy",
        FeatureGateId::SidecarContainers,
        20,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/initContainers/*/securityContext/procMount",
        FeatureGateId::ProcMountType,
        36,
        Some(&["Unmasked"]),
    ),
    (
        "/spec/jobTemplate/spec/template/spec/initContainers/*/volumeMounts/*/mountPropagation",
        FeatureGateId::MountPropagation,
        20,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/overhead",
        FeatureGateId::PodOverhead,
        24,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/preemptionPolicy",
        FeatureGateId::NonPreemptingPriority,
        24,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/runtimeClassName",
        FeatureGateId::RuntimeClass,
        20,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/securityContext/fsGroupChangePolicy",
        FeatureGateId::ConfigurableFSGroupPolicy,
        23,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/setHostnameAsFQDN",
        FeatureGateId::SetHostnameAsFQDN,
        22,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/volumes/*/csi",
        FeatureGateId::CSIInlineVolume,
        25,
        None,
    ),
    (
        "/spec/jobTemplate/spec/template/spec/volumes/*/ephemeral",
        FeatureGateId::GenericEphemeralVolume,
        23,
        None,
    ),
    (
        "/spec/jobTemplate/spec/ttlSecondsAfterFinished",
        FeatureGateId::TTLAfterFinished,
        23,
        None,
    ),
];
pub(super) fn validate(tree: &TreeNode, kind: &str, api: &str, target: &TargetProfile, out: &mut dyn FindingSink) {
    let rules = match (kind, api) {
        ("Pod", "v1") => RULES_0,
        ("Deployment", "apps/v1") => RULES_1,
        ("StatefulSet", "apps/v1") => RULES_2,
        ("DaemonSet", "apps/v1") => RULES_3,
        ("ReplicaSet", "apps/v1") => RULES_4,
        ("ReplicationController", "v1") => RULES_5,
        ("Job", "batch/v1") => RULES_6,
        ("CronJob", "batch/v1") => RULES_7,
        ("CronJob", "batch/v1beta1") => RULES_8,
        _ => return,
    };
    for (pointer, gate, since, values) in rules {
        if let Ok(pattern) = FieldPath::parse(pointer) {
            visit(
                tree,
                &pattern.0,
                &FieldPath::default(),
                &GateCheck {
                    gate: *gate,
                    since: *since,
                    values: *values,
                    target,
                },
                out,
            );
        }
    }
}
struct GateCheck<'a> {
    gate: FeatureGateId,
    since: u8,
    values: Option<&'static [&'static str]>,
    target: &'a TargetProfile,
}
fn visit(node: &TreeNode, remaining: &[String], path: &FieldPath, check: &GateCheck<'_>, out: &mut dyn FindingSink) {
    let Some((first, rest)) = remaining.split_first() else {
        if check
            .values
            .is_some_and(|values| node.as_str().is_none_or(|v| !values.contains(&v)))
        {
            return;
        }
        let code = if check.gate == FeatureGateId::ProcMountType {
            Some(FindingCode::UnadmittedField)
        } else if check.target.kubernetes.minor() < check.since {
            Some(FindingCode::UnavailableField)
        } else if check.target.feature_gates.resolve(check.gate, check.target.kubernetes)
            != Ok(FeatureGateState::Enabled)
        {
            Some(FindingCode::FeatureGateRequired)
        } else {
            None
        };
        if let Some(code) = code {
            out.push(Finding::error(code, Phase::Validation).at_path(path.clone()));
        }
        return;
    };
    if first == "*" {
        if let Some(list) = node.as_sequence() {
            for (i, n) in list.iter().enumerate() {
                visit(n, rest, &path.child(i.to_string()), check, out);
            }
        } else if let Some(map) = node.as_mapping() {
            for (k, n) in map {
                visit(n, rest, &path.child(k.clone()), check, out);
            }
        }
    } else if let Some(n) = node.get(first) {
        visit(n, rest, &path.child(first.clone()), check, out);
    }
}
